/**
 * @spfn/auth - Verification Codes Entity
 *
 * Stores verification codes for email and phone verification
 * Codes expire after a configurable time period
 */

import { text, index, integer, check } from 'drizzle-orm/pg-core';
import { id, timestamps, enumText, utcTimestamp } from '@spfn/core/db';
import { sql } from 'drizzle-orm';
import { authSchema } from './schema';

/**
 * Verification target type enum values
 * Single source of truth for verification target types
 */
export const VERIFICATION_TARGET_TYPES = ['email', 'phone'] as const;

/**
 * Verification target type derived from the const array
 */
export type VerificationTargetType = typeof VERIFICATION_TARGET_TYPES[number];

/**
 * Verification purpose enum values
 * Single source of truth for verification purposes
 */
export const VERIFICATION_PURPOSES = ['registration', 'login', 'password_reset', 'email_change', 'phone_change'] as const;

/**
 * Verification purpose type derived from the const array
 */
export type VerificationPurpose = typeof VERIFICATION_PURPOSES[number];

export const verificationCodes = authSchema.table('verification_codes',
    {
        id: id(),

        // Target (email or phone)
        // Email address or E.164 phone number (+821012345678)
        target: text('target').notNull(),
        targetType: enumText('target_type', VERIFICATION_TARGET_TYPES).notNull(),

        // Verification code
        // Default: 6-digit numeric code (configurable)
        // Generated by: crypto.randomInt(100000, 999999)
        code: text('code').notNull(),

        // Purpose of verification
        // Used to: prevent code reuse across different flows
        purpose: enumText('purpose', VERIFICATION_PURPOSES).notNull(),

        // Expiration timestamp
        // Default: 15 minutes from creation
        // Background job should clean up expired codes
        expiresAt: utcTimestamp('expires_at').notNull(),

        // Usage tracking
        // Timestamp when code was successfully used
        // null = not yet used, timestamp = used and no longer valid
        usedAt: utcTimestamp('used_at'),

        // Failed verification attempts counter
        // Incremented on each failed verification
        // Max attempts: 5 (enforced by check constraint)
        // Used for: rate limiting, security monitoring
        attempts: integer('attempts').notNull().default(0),

        ...timestamps(),
    },
    (table) => [
        // Database constraints
        // Limit verification attempts to prevent brute force attacks
        check('attempts_limit_check', sql`${table.attempts} >= 0 AND ${table.attempts} <= 10`),

        // Index for quick lookup by target and purpose
        index('target_purpose_idx')
            .on(table.target, table.purpose, table.expiresAt),
    ]
);

// Type exports
export type VerificationCode = typeof verificationCodes.$inferSelect;
export type NewVerificationCode = typeof verificationCodes.$inferInsert;

// Helper type with computed status
export type ActiveVerificationCode = VerificationCode & {
    isExpired: boolean;
    isUsed: boolean;
    attemptsRemaining: number;
    canRetry: boolean;
};