/**
 * Auto-generated Router Metadata
 *
 * Generated by @spfn/core router codegen
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten on next generation
 */

/**
 * Route metadata extracted at build time
 *
 * This pure data object contains only method and path information,
 * making it safe to import in client-side code without bundling server logic.
 *
 * Usage:
 * ```typescript
 * import { createApi } from '@spfn/core/client/nextjs';
 * import { appMetadata } from '@/server/router.metadata';
 * import type { AppRouter } from '@/server/router';
 *
 * const api = createApi<AppRouter>({
 *   baseUrl: '/api/actions',
 *   metadata: appMetadata
 * });
 * ```
 */
export const appMetadata = {
    "errorNotFound": { method: "GET", path: "/errors/not-found" },
    "errorUnauthorized": { method: "GET", path: "/errors/unauthorized" },
    "errorForbidden": { method: "GET", path: "/errors/forbidden" },
    "errorConflict": { method: "POST", path: "/errors/conflict" },
    "errorUnprocessable": { method: "POST", path: "/errors/unprocessable" },
    "errorCustom": { method: "POST", path: "/errors/custom" },
    "listErrorExamples": { method: "GET", path: "/errors" },
    "listExamples": { method: "GET", path: "/examples" },
    "getExample": { method: "GET", path: "/examples/:id" },
    "createExample": { method: "POST", path: "/examples" },
    "updateExample": { method: "PUT", path: "/examples/:id" },
    "deleteExample": { method: "DELETE", path: "/examples/:id" },
    "getHealth": { method: "GET", path: "/health" },
    "getRoot": { method: "GET", path: "/" },
    "listTeams": { method: "GET", path: "/teams" },
    "getTeam": { method: "GET", path: "/teams/:id" },
    "createTeam": { method: "POST", path: "/teams" },
    "updateTeam": { method: "PUT", path: "/teams/:id" },
    "deleteTeam": { method: "DELETE", path: "/teams/:id" },
} as const;
