/**
 * Router Metadata Emitter
 *
 * Generates router metadata file for client-side usage
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs';
import { dirname } from 'path';
import type { RouterMetadata } from './scanner';

export interface EmitterOptions
{
    metadata: RouterMetadata;
    outputPath: string;
    baseUrl: string;
    routerImportPath: string;
}

/**
 * Generate router metadata file
 *
 * Only writes if content has changed to avoid unnecessary rebuilds
 */
export async function generateApiClient(options: EmitterOptions): Promise<void>
{
    const { metadata, outputPath } = options;

    const code = generateMetadataCode(metadata);

    // Check if file exists and content is identical
    if (existsSync(outputPath))
    {
        const existingContent = readFileSync(outputPath, 'utf-8');
        if (existingContent === code)
        {
            // No changes, skip writing
            return;
        }
    }

    // Ensure output directory exists
    mkdirSync(dirname(outputPath), { recursive: true });

    // Write to file
    writeFileSync(outputPath, code, 'utf-8');
}

/**
 * Generate metadata-only TypeScript code
 */
function generateMetadataCode(metadata: RouterMetadata): string
{
    const { routes } = metadata;

    // Generate metadata object
    const metadataEntries = Object.entries(routes)
        .map(([name, { method, path }]) =>
            `    ${JSON.stringify(name)}: { method: ${JSON.stringify(method)}, path: ${JSON.stringify(path)} },`
        )
        .join('\n');

    return `/**
 * Auto-generated Router Metadata
 *
 * Generated by @spfn/core router codegen
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten on next generation
 */

/**
 * Route metadata extracted at build time
 *
 * This pure data object contains only method and path information,
 * making it safe to import in client-side code without bundling server logic.
 *
 * Usage:
 * \`\`\`typescript
 * import { createApi } from '@spfn/core/nextjs';
 * import { appMetadata } from '@/server/router.metadata';
 * import type { AppRouter } from '@/server/router';
 *
 * const api = createApi<AppRouter>({
 *   baseUrl: '/api/actions',
 *   metadata: appMetadata
 * });
 * \`\`\`
 */
export const appMetadata = {
${metadataEntries}
} as const;
`;
}