/**
 * API Client Emitter
 *
 * Generates API client code with pre-extracted route metadata
 */

import { writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import type { RouterMetadata } from './scanner';

export interface EmitterOptions
{
    metadata: RouterMetadata;
    outputPath: string;
    baseUrl: string;
    routerImportPath: string;
}

/**
 * Generate API client file
 */
export async function generateApiClient(options: EmitterOptions): Promise<void>
{
    const { metadata, outputPath, baseUrl, routerImportPath } = options;

    const code = generateCode(metadata, baseUrl, routerImportPath);

    // Ensure output directory exists
    mkdirSync(dirname(outputPath), { recursive: true });

    // Write to file
    writeFileSync(outputPath, code, 'utf-8');
}

/**
 * Generate TypeScript code
 */
function generateCode(
    metadata: RouterMetadata,
    baseUrl: string,
    routerImportPath: string
): string
{
    const { routes, routerTypeName } = metadata;

    // Generate metadata object
    const metadataEntries = Object.entries(routes)
        .map(([name, { method, path }]) =>
            `    ${JSON.stringify(name)}: { method: ${JSON.stringify(method)}, path: ${JSON.stringify(path)} },`
        )
        .join('\n');

    return `/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core router codegen
 * Source: ${routerImportPath}
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten on next generation
 */

import { createApi } from '@spfn/core/client/nextjs';
import {
    ErrorRegistry,
    HttpError,
    BadRequestError,
    ValidationError,
    UnauthorizedError,
    ForbiddenError,
    NotFoundError,
    ConflictError,
    TooManyRequestsError,
    UnprocessableEntityError,
    InternalServerError,
    ServiceUnavailableError,
} from '@spfn/core/errors';
import type { ${routerTypeName} } from '${routerImportPath}';

/**
 * Route metadata extracted at build time
 *
 * This allows the client to work without importing the actual router object,
 * making it safe to use in Server Components without bundling server code.
 */
const routeMetadata = {
${metadataEntries}
} as const;

/**
 * Error registry with built-in HTTP errors
 *
 * Enables automatic error deserialization on the client with instanceof checks.
 * To register custom errors, import them and call errorRegistry.register(CustomError).
 */
const errorRegistry = new ErrorRegistry();

// Register all built-in HTTP errors from @spfn/core
errorRegistry.registerAll([
    HttpError,
    BadRequestError,
    ValidationError,
    UnauthorizedError,
    ForbiddenError,
    NotFoundError,
    ConflictError,
    TooManyRequestsError,
    UnprocessableEntityError,
    InternalServerError,
    ServiceUnavailableError,
]);

// TODO: Register custom application errors here
// Example:
// import { CustomError } from '@/server/errors/custom-error';
// errorRegistry.register(CustomError);

/**
 * Pre-configured type-safe API client
 *
 * Usage:
 * \`\`\`typescript
 * import { api } from '@/lib/api-client';
 *
 * // Basic call
 * const user = await api.getUser
 *     .params({ id: '123' })
 *     .call();
 *
 * // Error handling with instanceof
 * try {
 *     await api.someRoute.call();
 * } catch (error) {
 *     if (error instanceof NotFoundError) {
 *         console.log('Resource not found');
 *     } else if (error instanceof ValidationError) {
 *         console.log('Validation failed:', error.fields);
 *     }
 * }
 * \`\`\`
 *
 * Works in:
 * - Server Components (no router import needed)
 * - Client Components (proxied through /api/actions)
 * - Server Actions
 * - Route Handlers
 */
export const api = createApi<${routerTypeName}>({
    baseUrl: '${baseUrl}',
    metadata: routeMetadata,
    errorRegistry,
});

/**
 * Export api as default for convenience
 */
export default api;

/**
 * Export errorRegistry for registering custom errors
 */
export { errorRegistry };
`;
}