import { Command } from 'commander';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { execa } from 'execa';
import chalk from 'chalk';
import { logger } from '../utils/logger.js';
import { detectPackageManager } from '../utils/package-manager.js';

interface StartOptions
{
    serverOnly?: boolean;
    nextOnly?: boolean;
    port?: string;
    host?: string;
    allowPendingMigrations?: boolean;
}

export const startCommand = new Command('start')
    .description('Start SPFN production server (Next.js + Hono)')
    .option('--server-only', 'Run only SPFN server (skip Next.js)')
    .option('--next-only', 'Run only Next.js (skip SPFN server)')
    // No defaults on purpose. A default here is indistinguishable from a value
    // the operator typed, and it was forwarded as SPFN_PORT either way — which
    // overrode whatever the app declared in its own server.config. Left unset,
    // the app's configuration decides and these flags override it.
    .option('-p, --port <port>', 'Server port (default: the app\'s server.config, then 4000)')
    .option('-h, --host <host>', 'Server host (default: the app\'s server.config, then localhost)')
    .option('--allow-pending-migrations', 'Start even when migrations are pending (they are listed as a warning)')
    .action(async (options: StartOptions) =>
    {
        // Set NODE_ENV to production (Next.js style)
        if (!process.env.NODE_ENV) 
        {
            process.env.NODE_ENV = 'production';
        }

        const cwd = process.cwd();

        // Check if package.json exists
        const packageJsonPath = join(cwd, 'package.json');
        let hasNext = false;

        if (existsSync(packageJsonPath))
        {
            const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
            hasNext = !!(packageJson.dependencies?.next || packageJson.devDependencies?.next);
        }

        // Check if SPFN server built
        const builtServerDir = join(cwd, '.spfn', 'server');
        const hasBuiltServer = existsSync(builtServerDir);

        // Check if Next.js built
        const nextBuildDir = join(cwd, '.next');
        const hasNextBuild = existsSync(nextBuildDir);

        // Validate build artifacts
        if (!options.nextOnly && !hasBuiltServer)
        {
            logger.error('.spfn/server directory not found. Please run "spfn build" first.');
            process.exit(1);
        }

        if (!options.serverOnly && hasNext && !hasNextBuild)
        {
            logger.error('.next directory not found. Please run "spfn build" first.');
            process.exit(1);
        }

        const pm = detectPackageManager(cwd);

        // Use pre-built production server entry (generated by spfn build)
        const serverEntry = join(cwd, '.spfn', 'prod-server.mjs');

        if (!existsSync(serverEntry))
        {
            logger.error('.spfn/prod-server.mjs not found. Please run "spfn build" first.');
            process.exit(1);
        }

        // Forward only what was actually asked for. Setting these unconditionally
        // is what made the app's own server.config unreachable.
        if (options.port)
        {
            process.env.SPFN_PORT = options.port;
        }

        if (options.host)
        {
            process.env.SPFN_HOST = options.host;
        }

        // Refuse a boot whose database is behind the code it is about to serve.
        // Skipped for --next-only: no SPFN server starts, so nothing can drift.
        if (!options.nextOnly)
        {
            const { checkPendingMigrationsBeforeStart } = await import('../utils/migration-status.js');
            const migrationCheck = await checkPendingMigrationsBeforeStart(
                cwd,
                process.env.DATABASE_URL,
                options.allowPendingMigrations === true,
            );

            if (migrationCheck.block)
            {
                process.exit(1);
            }

            if (migrationCheck.allowPending)
            {
                // The server process re-decides for itself — hand it the same answer.
                process.env.SPFN_ALLOW_PENDING_MIGRATIONS = 'true';
            }
        }

        // Run server only mode
        if (options.serverOnly || !hasNext)
        {
            // The address is not printed here: without the flags it is the app's
            // server.config that decides, and this process does not read it. The
            // server prints its own banner with the address it actually bound.
            logger.info('Starting SPFN Server (production)\n');

            try
            {
                await execa('node', [serverEntry], {
                    stdio: 'inherit',
                    cwd,
                    env: { ...process.env },
                });
            }
            catch (error)
            {
                logger.error(`Failed to start server: ${error}`);
                process.exit(1);
            }

            return;
        }

        // Run Next.js only mode
        if (options.nextOnly)
        {
            logger.info('Starting Next.js (production) on http://0.0.0.0:3790\n');

            try
            {
                await execa('npx', ['next', 'start', '-H', '0.0.0.0', '-p', '3790'], {
                    stdio: 'inherit',
                    cwd,
                });
            }
            catch (error)
            {
                logger.error(`Failed to start Next.js: ${error}`);
                process.exit(1);
            }

            return;
        }

        // Run both Next.js + Hono server.
        // Each command is a single argv element for concurrently, which spawns it
        // through its own shell — quote the path so spaces in cwd survive.
        const nextCmd = 'next start -H 0.0.0.0 -p 3790';
        const serverCmd = `node "${serverEntry}"`;

        console.log(chalk.blue.bold('\n🚀 Starting SPFN production server...\n'));
        logger.info('Next.js: http://0.0.0.0:3790');
        logger.info('SPFN API: announced by the server below\n');

        try
        {
            await execa(pm === 'npm' ? 'npx' : pm,
                pm === 'npm'
                    ? ['concurrently', '--raw', '--kill-others', nextCmd, serverCmd]
                    : ['exec', 'concurrently', '--raw', '--kill-others', nextCmd, serverCmd],
                {
                    stdio: 'inherit',
                    cwd,
                    env: { ...process.env },
                },
            );
        }
        catch (error)
        {
            // Concurrently was killed by user (Ctrl+C), this is expected
            const execError = error as { exitCode?: number };
            if (execError.exitCode === 130)
            {
                process.exit(0);
            }

            logger.error(`Failed to start production servers: ${error}`);
            process.exit(1);
        }
    });
