/**
 * SPFN RPC Proxy Route
 *
 * Forwards client `api.*.call()` requests to the SPFN API server, resolving each
 * route from the generated routeMap and forwarding cookies/interceptors.
 *
 * The routeMap is generated by codegen (`pnpm codegen`) from src/server/router.ts.
 */

import { createRpcProxy } from '@spfn/core/nextjs/server';
import { routeMap } from '@/generated/route-map';

export const { GET, POST } = createRpcProxy({ routeMap });
