import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import remarkRehype from 'remark-rehype';
import rehypeSanitize, { defaultSchema } from 'rehype-sanitize';
import rehypeSlug from 'rehype-slug';
import rehypeShiki from '@shikijs/rehype';
import rehypeStringify from 'rehype-stringify';
import { rehypeRewriteRefs, type RewriteContext } from './rewrite';

/**
 * Sanitization first, decoration after: everything downstream of sanitize
 * (heading ids, shiki output) is generated by us, not by the repo.
 *
 * - `clobberPrefix: ''` keeps heading/footnote ids usable as plain '#anchor'
 *   links (GitHub's 'user-content-' prefixing breaks them without client JS).
 * - `language-*` classes survive so the highlighter can pick up the language.
 */
const schema: typeof defaultSchema = {
    ...defaultSchema,
    clobberPrefix: '',
    attributes: {
        ...defaultSchema.attributes,
        code: [['className', /^language-/]],
    },
};

/** Dual-theme highlighting: light styles inline, dark via --shiki-dark variables (flipped in theme CSS). */
const shikiOptions = {
    themes: { light: 'github-light', dark: 'github-dark' },
    defaultColor: 'light' as const,
    fallbackLanguage: 'text',
};

function buildProcessor(context?: RewriteContext)
{
    const processor = unified()
        .use(remarkParse)
        .use(remarkGfm)
        .use(remarkRehype);

    if (context)
    {
        processor.use(rehypeRewriteRefs, context);
    }

    return processor
        .use(rehypeSanitize, schema)
        .use(rehypeSlug)
        .use(rehypeShiki, shikiOptions)
        .use(rehypeStringify);
}

/**
 * Markdown → sanitized HTML. Raw HTML (script/iframe/event handlers) is stripped —
 * published repos are untrusted input. With a context, relative links to sibling
 * markdown files become route links and `public/` references become asset URLs.
 */
export async function renderMarkdown(markdown: string, context?: RewriteContext): Promise<string>
{
    return String(await buildProcessor(context).process(markdown));
}
