/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-16T03:52:55.852Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core/route/types';

import { getAdminLabelContract } from '@/lib/contracts/labels';

// ============================================
// Types
// ============================================

export type GetAdminLabelResponse = InferContract<typeof getAdminLabelContract>['response'];
export type GetAdminLabelParams = InferContract<typeof getAdminLabelContract>['params'];

// ============================================
// API Functions
// ============================================

/**
 * GET /_cms/labels/:id/admin
 */
export const getAdminLabel = (options: { params: GetAdminLabelParams }) => client.call(getAdminLabelContract, options);

