/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-01T16:47:27.110Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { getLabelByKeyContract } from '@/lib/contracts/labels';

// ============================================
// Types
// ============================================

export type GetLabelByKeyResponse = InferContract<typeof getLabelByKeyContract>['response'];
export type GetLabelByKeyParams = InferContract<typeof getLabelByKeyContract>['params'];

/**
 * CmsLabelsByKey API
 */
export const CmsLabelsByKey = {
        /**
         * GET /_cms/labels/by-key/:key
         */
        getById: (options: { params: GetLabelByKeyParams }) => client.call(getLabelByKeyContract, options),
} as const;
