/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-01T16:11:17.810Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { getPublishedCacheContract } from '@/lib/contracts/published-cache';

// ============================================
// Types
// ============================================

export type GetPublishedCacheResponse = InferContract<typeof getPublishedCacheContract>['response'];
export type GetPublishedCacheQuery = InferContract<typeof getPublishedCacheContract>['query'];

/**
 * CmsPublishedCache API
 */
export const CmsPublishedCache = {
        /**
         * GET /_cms/published-cache
         */
        get: (options: { query?: GetPublishedCacheQuery }) => client.call(getPublishedCacheContract, options),
} as const;
