/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-16T03:52:55.854Z
 */

export { client } from '@spfn/core/client';

export type { GetLabelsResponse, GetLabelsQuery, CreateLabelResponse, CreateLabelBody, GetLabelResponse, GetLabelParams, UpdateLabelResponse, UpdateLabelParams, UpdateLabelBody, DeleteLabelResponse, DeleteLabelParams } from './cms-labels';
export type { GetLabelByKeyResponse, GetLabelByKeyParams } from './cms-labels-by-key';
export type { PublishLabelResponse, PublishLabelParams, PublishLabelBody } from './cms-labels-publish';
export type { GetAdminLabelResponse, GetAdminLabelParams } from './cms-labels-admin';
export type { GetLabelVersionsResponse, GetLabelVersionsParams } from './cms-labels-versions';
export type { GetPublishedCacheResponse, GetPublishedCacheQuery, UpsertPublishedCacheResponse, UpsertPublishedCacheBody } from './cms-published-cache';
export type { SaveValuesResponse, SaveValuesParams, SaveValuesBody, GetValuesResponse, GetValuesQuery, GetValuesParams } from './cms-values';

import { getLabels, createLabel, getLabel, updateLabel, deleteLabel } from './cms-labels';
import { getLabelByKey } from './cms-labels-by-key';
import { publishLabel } from './cms-labels-publish';
import { getAdminLabel } from './cms-labels-admin';
import { getLabelVersions } from './cms-labels-versions';
import { getPublishedCache, upsertPublishedCache } from './cms-published-cache';
import { saveValues, getValues } from './cms-values';

/**
 * Type-safe API client
 */
export const cmsApi = {
    getLabels,
    createLabel,
    getLabel,
    updateLabel,
    deleteLabel,
    getLabelByKey,
    publishLabel,
    getAdminLabel,
    getLabelVersions,
    getPublishedCache,
    upsertPublishedCache,
    saveValues,
    getValues
} as const;
