/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-01T16:11:17.811Z
 */

export { client } from '@spfn/core/client';

export * from './CmsLabels.js';
export * from './CmsLabelsByKey.js';
export * from './CmsPublishedCache.js';
export * from './CmsValues.js';

import { CmsLabels } from './CmsLabels.js';
import { CmsLabelsByKey } from './CmsLabelsByKey.js';
import { CmsPublishedCache } from './CmsPublishedCache.js';
import { CmsValues } from './CmsValues.js';

/**
 * Type-safe API client
 */
export const api = {
    CmsLabels,
    CmsLabelsByKey,
    CmsPublishedCache,
    CmsValues
} as const;
