/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-02T13:40:31.266Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { registerContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type RegisterResponse = InferContract<typeof registerContract>['response'];
export type RegisterBody = InferContract<typeof registerContract>['body'];

/**
 * AuthRegister API
 */
export const AuthRegister = {
        /**
         * POST /_auth/register
         */
        post: (options: { body: RegisterBody }) => client.call(registerContract, options),
} as const;
