/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-02T13:40:31.267Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { loginContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type LoginResponse = InferContract<typeof loginContract>['response'];
export type LoginBody = InferContract<typeof loginContract>['body'];

/**
 * AuthLogin API
 */
export const AuthLogin = {
        /**
         * POST /_auth/login
         */
        post: (options: { body: LoginBody }) => client.call(loginContract, options),
} as const;
