/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-02T13:40:31.267Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { changePasswordContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type ChangePasswordResponse = InferContract<typeof changePasswordContract>['response'];
export type ChangePasswordBody = InferContract<typeof changePasswordContract>['body'];

/**
 * AuthPassword API
 */
export const AuthPassword = {
        /**
         * PUT /_auth/password
         */
        put: (options: { body: ChangePasswordBody }) => client.call(changePasswordContract, options),
} as const;
