/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-10T11:11:07.524Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core/route/types';

import { getUserProfileContract } from '@/lib/contracts/users';

// ============================================
// Types
// ============================================

export type GetUserProfileResponse = InferContract<typeof getUserProfileContract>['response'];

// ============================================
// API Functions
// ============================================

/**
 * GET /_auth/users/profile
 */
export const getUserProfile = () => client.call(getUserProfileContract);

