/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-16T07:53:55.399Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core/route/types';

import { deleteInvitationContract } from '@/lib/contracts/invitation';

// ============================================
// Types
// ============================================

export type DeleteInvitationResponse = InferContract<typeof deleteInvitationContract>['response'];
export type DeleteInvitationBody = InferContract<typeof deleteInvitationContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/invitations/delete
 */
export const deleteInvitation = (options: { body: DeleteInvitationBody }) => client.call(deleteInvitationContract, options);

