/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-02T13:40:31.266Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { verifyCodeContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type VerifyCodeResponse = InferContract<typeof verifyCodeContract>['response'];
export type VerifyCodeBody = InferContract<typeof verifyCodeContract>['body'];

/**
 * AuthCodesVerify API
 */
export const AuthCodesVerify = {
        /**
         * POST /_auth/codes/verify
         */
        post: (options: { body: VerifyCodeBody }) => client.call(verifyCodeContract, options),
} as const;
