/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-10T05:37:38.251Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { registerContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type RegisterResponse = InferContract<typeof registerContract>['response'];
export type RegisterBody = InferContract<typeof registerContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/register
 */
export const register = (options: { body: RegisterBody }) => client.call(registerContract, options);

