/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-10T05:37:38.252Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { getInvitationContract, createInvitationContract, listInvitationsContract } from '@/lib/contracts/invitation';

// ============================================
// Types
// ============================================

export type GetInvitationResponse = InferContract<typeof getInvitationContract>['response'];
export type GetInvitationParams = InferContract<typeof getInvitationContract>['params'];

export type CreateInvitationResponse = InferContract<typeof createInvitationContract>['response'];
export type CreateInvitationBody = InferContract<typeof createInvitationContract>['body'];

export type ListInvitationsResponse = InferContract<typeof listInvitationsContract>['response'];
export type ListInvitationsQuery = InferContract<typeof listInvitationsContract>['query'];

// ============================================
// API Functions
// ============================================

/**
 * GET /_auth/invitations/:token
 */
export const getInvitation = (options: { params: GetInvitationParams }) => client.call(getInvitationContract, options);

/**
 * POST /_auth/invitations
 */
export const createInvitation = (options: { body: CreateInvitationBody }) => client.call(createInvitationContract, options);

/**
 * GET /_auth/invitations
 */
export const listInvitations = (options: { query?: ListInvitationsQuery }) => client.call(listInvitationsContract, options);

