/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-10T05:37:38.253Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { resendInvitationContract } from '@/lib/contracts/invitation';

// ============================================
// Types
// ============================================

export type ResendInvitationResponse = InferContract<typeof resendInvitationContract>['response'];
export type ResendInvitationBody = InferContract<typeof resendInvitationContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/invitations/resend
 */
export const resendInvitation = (options: { body: ResendInvitationBody }) => client.call(resendInvitationContract, options);

