/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-02T13:40:31.265Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { sendVerificationCodeContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type SendVerificationCodeResponse = InferContract<typeof sendVerificationCodeContract>['response'];
export type SendVerificationCodeBody = InferContract<typeof sendVerificationCodeContract>['body'];

/**
 * AuthCodes API
 */
export const AuthCodes = {
        /**
         * POST /_auth/codes
         */
        post: (options: { body: SendVerificationCodeBody }) => client.call(sendVerificationCodeContract, options),
} as const;
