/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-16T05:27:26.684Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core/route/types';

import { getAuthSessionContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type GetAuthSessionResponse = InferContract<typeof getAuthSessionContract>['response'];

// ============================================
// API Functions
// ============================================

/**
 * GET /_auth/session
 */
export const getAuthSession = () => client.call(getAuthSessionContract);

