/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-09T12:30:02.320Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { checkAccountExistsContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type CheckAccountExistsResponse = InferContract<typeof checkAccountExistsContract>['response'];
export type CheckAccountExistsBody = InferContract<typeof checkAccountExistsContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/exists
 */
export const checkAccountExists = (options: { body: CheckAccountExistsBody }) => client.call(checkAccountExistsContract, options);

