/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-02T13:40:31.267Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { rotateKeyContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type RotateKeyResponse = InferContract<typeof rotateKeyContract>['response'];
export type RotateKeyBody = InferContract<typeof rotateKeyContract>['body'];

/**
 * AuthKeysRotate API
 */
export const AuthKeysRotate = {
        /**
         * POST /_auth/keys/rotate
         */
        post: (options: { body: RotateKeyBody }) => client.call(rotateKeyContract, options),
} as const;
