/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-09T12:30:02.323Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { getMeContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type GetMeResponse = InferContract<typeof getMeContract>['response'];
export type GetMeBody = InferContract<typeof getMeContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * GET /_auth/me
 */
export const getMe = (options: { body: GetMeBody }) => client.call(getMeContract, options);

