/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-02T13:40:31.266Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { checkAccountExistsContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type CheckAccountExistsResponse = InferContract<typeof checkAccountExistsContract>['response'];
export type CheckAccountExistsBody = InferContract<typeof checkAccountExistsContract>['body'];

/**
 * AuthExists API
 */
export const AuthExists = {
        /**
         * POST /_auth/exists
         */
        post: (options: { body: CheckAccountExistsBody }) => client.call(checkAccountExistsContract, options),
} as const;
