/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-09T04:21:56.957Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { loginContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type LoginResponse = InferContract<typeof loginContract>['response'];
export type LoginBody = InferContract<typeof loginContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/login
 */
export const login = (options: { body: LoginBody }) => client.call(loginContract, options);

