/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-09T04:21:56.957Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { changePasswordContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type ChangePasswordResponse = InferContract<typeof changePasswordContract>['response'];
export type ChangePasswordBody = InferContract<typeof changePasswordContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * PUT /_auth/password
 */
export const changePassword = (options: { body: ChangePasswordBody }) => client.call(changePasswordContract, options);

