/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-10T11:11:07.523Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core/route/types';

import { rotateKeyContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type RotateKeyResponse = InferContract<typeof rotateKeyContract>['response'];
export type RotateKeyBody = InferContract<typeof rotateKeyContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/keys/rotate
 */
export const rotateKey = (options: { body: RotateKeyBody }) => client.call(rotateKeyContract, options);

