/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-09T04:21:56.958Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { cancelInvitationContract } from '@/lib/contracts/invitation';

// ============================================
// Types
// ============================================

export type CancelInvitationResponse = InferContract<typeof cancelInvitationContract>['response'];
export type CancelInvitationBody = InferContract<typeof cancelInvitationContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/invitations/cancel
 */
export const cancelInvitation = (options: { body: CancelInvitationBody }) => client.call(cancelInvitationContract, options);

