/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-09T12:30:02.322Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { logoutContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type LogoutResponse = InferContract<typeof logoutContract>['response'];
export type LogoutBody = InferContract<typeof logoutContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/logout
 */
export const logout = (options: { body: LogoutBody }) => client.call(logoutContract, options);

