/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-10T11:11:07.524Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core/route/types';

import { acceptInvitationContract } from '@/lib/contracts/invitation';

// ============================================
// Types
// ============================================

export type AcceptInvitationResponse = InferContract<typeof acceptInvitationContract>['response'];
export type AcceptInvitationBody = InferContract<typeof acceptInvitationContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/invitations/accept
 */
export const acceptInvitation = (options: { body: AcceptInvitationBody }) => client.call(acceptInvitationContract, options);

