/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-16T05:27:26.682Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core/route/types';

import { verifyCodeContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type VerifyCodeResponse = InferContract<typeof verifyCodeContract>['response'];
export type VerifyCodeBody = InferContract<typeof verifyCodeContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/codes/verify
 */
export const verifyCode = (options: { body: VerifyCodeBody }) => client.call(verifyCodeContract, options);

