/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-09T12:30:02.318Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { sendVerificationCodeContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type SendVerificationCodeResponse = InferContract<typeof sendVerificationCodeContract>['response'];
export type SendVerificationCodeBody = InferContract<typeof sendVerificationCodeContract>['body'];

// ============================================
// API Functions
// ============================================

/**
 * POST /_auth/codes
 */
export const sendVerificationCode = (options: { body: SendVerificationCodeBody }) => client.call(sendVerificationCodeContract, options);

