/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-02T13:40:31.267Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { logoutContract } from '@/lib/contracts/auth';

// ============================================
// Types
// ============================================

export type LogoutResponse = InferContract<typeof logoutContract>['response'];
export type LogoutBody = InferContract<typeof logoutContract>['body'];

/**
 * AuthLogout API
 */
export const AuthLogout = {
        /**
         * POST /_auth/logout
         */
        post: (options: { body: LogoutBody }) => client.call(logoutContract, options),
} as const;
