/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-10T05:37:38.253Z
 */

export { client } from '@spfn/core/client';

export type { SendVerificationCodeResponse, SendVerificationCodeBody } from './auth-codes';
export type { VerifyCodeResponse, VerifyCodeBody } from './auth-codes-verify';
export type { CheckAccountExistsResponse, CheckAccountExistsBody } from './auth-exists';
export type { RegisterResponse, RegisterBody } from './auth-register';
export type { LoginResponse, LoginBody } from './auth-login';
export type { LogoutResponse, LogoutBody } from './auth-logout';
export type { RotateKeyResponse, RotateKeyBody } from './auth-keys-rotate';
export type { ChangePasswordResponse, ChangePasswordBody } from './auth-password';
export type { GetMeResponse, GetMeBody } from './auth-me';
export type { GetInvitationResponse, GetInvitationParams, CreateInvitationResponse, CreateInvitationBody, ListInvitationsResponse, ListInvitationsQuery } from './auth-invitations';
export type { AcceptInvitationResponse, AcceptInvitationBody } from './auth-invitations-accept';
export type { CancelInvitationResponse, CancelInvitationBody } from './auth-invitations-cancel';
export type { ResendInvitationResponse, ResendInvitationBody } from './auth-invitations-resend';
export type { DeleteInvitationResponse, DeleteInvitationBody } from './auth-invitations-delete';

import { sendVerificationCode } from './auth-codes';
import { verifyCode } from './auth-codes-verify';
import { checkAccountExists } from './auth-exists';
import { register } from './auth-register';
import { login } from './auth-login';
import { logout } from './auth-logout';
import { rotateKey } from './auth-keys-rotate';
import { changePassword } from './auth-password';
import { getMe } from './auth-me';
import { getInvitation, createInvitation, listInvitations } from './auth-invitations';
import { acceptInvitation } from './auth-invitations-accept';
import { cancelInvitation } from './auth-invitations-cancel';
import { resendInvitation } from './auth-invitations-resend';
import { deleteInvitation } from './auth-invitations-delete';

/**
 * Type-safe API client
 */
export const authApi = {
    sendVerificationCode,
    verifyCode,
    checkAccountExists,
    register,
    login,
    logout,
    rotateKey,
    changePassword,
    getMe,
    getInvitation,
    createInvitation,
    listInvitations,
    acceptInvitation,
    cancelInvitation,
    resendInvitation,
    deleteInvitation
} as const;
