/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-11-02T13:40:31.267Z
 */

export { client } from '@spfn/core/client';

export * from './auth-codes.js';
export * from './auth-codes-verify.js';
export * from './auth-exists.js';
export * from './auth-register.js';
export * from './auth-login.js';
export * from './auth-logout.js';
export * from './auth-keys-rotate.js';
export * from './auth-password.js';

import { AuthCodes } from './auth-codes.js';
import { AuthCodesVerify } from './auth-codes-verify.js';
import { AuthExists } from './auth-exists.js';
import { AuthRegister } from './auth-register.js';
import { AuthLogin } from './auth-login.js';
import { AuthLogout } from './auth-logout.js';
import { AuthKeysRotate } from './auth-keys-rotate.js';
import { AuthPassword } from './auth-password.js';

/**
 * Type-safe API client
 */
export const authApi = {
    authCodes: AuthCodes,
    authCodesVerify: AuthCodesVerify,
    authExists: AuthExists,
    authRegister: AuthRegister,
    authLogin: AuthLogin,
    authLogout: AuthLogout,
    authKeysRotate: AuthKeysRotate,
    authPassword: AuthPassword
} as const;
