export const sharedExternal = [
    // Internal entrypoints (prevent bundling into each other)
    '@spfn/auth',
    '@spfn/auth/client',
    '@spfn/auth/config',
    '@spfn/auth/errors',
    '@spfn/auth/nextjs/api',
    '@spfn/auth/nextjs/client',
    '@spfn/auth/nextjs/server',
    '@spfn/auth/server',
    // External dependencies
    '@spfn/core',
    '@spfn/core/server',
    '@spfn/core/db',
    '@spfn/core/route',
    '@spfn/core/errors',
    '@spfn/core/logger',
    '@spfn/core/config',
    '@spfn/core/env',
    'drizzle-orm',
    'postgres',
    'bcryptjs',
    'jsonwebtoken',
    'next',
    'next/headers',
    'next/navigation',
    'server-only',
    'jose',
    'react',
    'react/jsx-runtime',
];
