import { getCliVersion } from '../utils/version.js';

/**
 * Marker lines that delimit the generated block.
 *
 * They are matched as whole lines at line start, never as a substring: prose
 * that merely mentions a marker inside a sentence must not be mistaken for the
 * block's boundary.
 */
export const BEGIN_MARKER = '<!-- spfn:agent-instructions:begin — generated by spfn dev; edits inside are overwritten -->';
export const END_MARKER = '<!-- spfn:agent-instructions:end -->';

/**
 * The instruction block, markers included.
 *
 * Every pointer here must resolve for the reader: files listed under
 * `node_modules/` are shipped by their package's `files` field, and the URLs
 * are pages the site actually serves — the module and guide names are the
 * routes `spfn.site.yaml` produces (`site/pages/docs/packages/core/*.md` and
 * the `docs/guides` mount), so re-check them there before editing this list.
 * The version line makes a stale block visible in a diff — a CLI bump
 * legitimately rewrites the block once.
 */
export function renderAgentInstructions(version: string = getCliVersion()): string
{
    return `${BEGIN_MARKER}
## SPFN conventions for coding agents

This is not the stack you know. An SPFN app looks like Next.js plus Drizzle, but
its idioms are not the ecosystem defaults, and code written from general priors
is wrong here. Read the docs below before writing server, data or auth code.

**Data access.** Every query goes through a repository extending
\`BaseRepository\` — \`this.db\` writes, \`this.readDb\` reads. Handlers and
services never import drizzle query builders directly.

\`\`\`typescript
import { BaseRepository } from '@spfn/core/db';
import { orders } from '../entities/order.entity';

export class OrderRepository extends BaseRepository
{
    async findByCustomer(customerId: bigint)
    {
        return this._findMany(orders, { where: { customerId } });
    }
}
\`\`\`

The scaffold's \`src/server/repositories/\` shows the shape.

**Transactions.** Wrap the route in \`Transactional()\`, or call
\`runInTransaction\` in a service or script. Never accept or pass a \`tx\`
parameter: repositories pick the transaction up from the async context. Side
effects that must not fire on a rollback go in \`onAfterCommit(...)\`.

**Auth.** Read the principal with \`getAuth(c)\` from \`@spfn/auth/server\`.
Authorization is declared route middleware —
\`.use([authenticate, requirePermissions('order:write')])\` — never an ad-hoc
check inside the handler body.

**Frontend data.** A page's initial data is awaited in a Server Component
through the isomorphic \`api.\` client; cookies forward automatically. Fetching
initial data from a \`'use client'\` component in \`useEffect\` is the
anti-pattern. Mutations go through server actions, or the same \`api.\` client
from a Client Component.

**Generated files.** Route maps under \`src/generated/\` come from
\`pnpm codegen\` — never hand-edit them. Migrations come from
\`spfn db generate\` off the entities; never hand-write migration SQL.

**Read before writing.** \`node_modules/@spfn/core/README.md\`,
\`node_modules/@spfn/core/src/db/README.md\`, \`node_modules/@spfn/auth/README.md\`.
Online: \`https://superfunction.xyz/docs/packages/core/<module>\` for cache,
codegen, config, db, env, errors, event, job, logger, middleware, nextjs, route,
security and server; \`https://superfunction.xyz/docs/guides/<guide>\` for
authentication, custom-generators, deployment, file-upload, monitoring and
websockets. Do not guess other paths — they 404.

<!-- spfn CLI v${version} -->
${END_MARKER}`;
}
