blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/spfn/spfn#readme
    about: Read the SPFN documentation
  - name: Discussions
    url: https://github.com/spfn/spfn/discussions
    about: Ask questions and discuss ideas with the community