/**
 * SPFN RPC Proxy Route
 *
 * Forwards client `api.*.call()` requests to the SPFN API server with automatic:
 * - Route resolution from the generated routeMap
 * - Cookie forwarding
 * - Interceptor execution
 *
 * The routeMap is generated by codegen (`pnpm codegen`) from src/server/router.ts.
 */

import { createRpcProxy } from '@spfn/core/nextjs/server';
import { eventRouteMap } from '@spfn/core/event';
import { routeMap } from '@/generated/route-map';

export const { GET, POST } = createRpcProxy({
    routeMap: { ...routeMap, ...eventRouteMap },
});
