import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { encodeBase64Url } from './jws';
import { formatPublicKeyEntry } from './keys';
import { LocalSigner } from './providers/local';
import { verifyJws } from './verify';
import type { SigningAlgorithm, VerifyFailureReason } from './types';

/**
 * `contracts/signing/vectors.json` is the fixed point other implementations
 * check themselves against: six tokens, the public keys that verify them, and
 * the verdict each one must produce.
 *
 * Regenerate it with `UPDATE_SIGNING_VECTORS=1 pnpm test`, and read the diff
 * — a change here is a change to what every holder of these vectors expects.
 */
const VECTORS_FILE = join(
    dirname(fileURLToPath(import.meta.url)),
    '../../../contracts/signing/vectors.json',
);

/** The instant every vector is judged at. */
const VERIFY_AT = 1_800_000_000_000;

/**
 * Fixed key material, so regenerating produces the same keys.
 *
 * The default algorithm comes first, so an implementation working through the
 * file in order meets Ed25519 before ES256. Test-only throwaway values with no
 * counterpart anywhere; the ES256 scalar starts at 0x01, which keeps it
 * comfortably below the curve order.
 */
const FIXTURE_KEYS = [
    {
        kid: 'vector-ed25519',
        alg: 'EdDSA' as SigningAlgorithm,
        material: '202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f',
    },
    {
        kid: 'vector-es256',
        alg: 'ES256' as SigningAlgorithm,
        material: '0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20',
    },
];

interface Vector
{
    name: string;
    kid: string;
    alg: SigningAlgorithm;
    token: string;
    expect: { ok: true } | { ok: false; reason: VerifyFailureReason };
}

interface VectorFile
{
    note: string;
    verifyAt: number;
    publicKeys: string;
    vectors: Vector[];
}

/** A signer over fixed material, loaded the way a deployment would load it. */
function fixtureSigner(kid: string, alg: SigningAlgorithm, material: string): LocalSigner
{
    process.env.SPFN_SIGNING_VECTOR_KEY = encodeBase64Url(Buffer.from(material, 'hex'));

    try
    {
        return new LocalSigner({ kid, alg, privateKey: { env: 'SPFN_SIGNING_VECTOR_KEY' } });
    }
    finally
    {
        delete process.env.SPFN_SIGNING_VECTOR_KEY;
    }
}

function flipSignatureByte(token: string): string
{
    const [head, body, signature] = token.split('.');
    const bytes = Buffer.from(signature, 'base64url');

    bytes[0] ^= 0x01;

    return `${head}.${body}.${encodeBase64Url(bytes)}`;
}

async function generate(): Promise<VectorFile>
{
    const publicKeys: string[] = [];
    const vectors: Vector[] = [];

    for (const { kid, alg, material } of FIXTURE_KEYS)
    {
        const signer = fixtureSigner(kid, alg, material);
        const label = alg === 'ES256' ? 'es256' : 'ed25519';

        publicKeys.push(formatPublicKeyEntry(await signer.publicKey()));

        const valid = await signer.sign({
            iss: 'spfn-signing-vectors',
            sub: 'vector',
            iat: 1_799_999_000,
            exp: 4_102_444_800,
        });
        const expired = await signer.sign({
            iss: 'spfn-signing-vectors',
            sub: 'vector',
            iat: 1_700_000_000,
            exp: 1_700_000_300,
        });

        vectors.push(
            { name: `${label}-valid`, kid, alg, token: valid, expect: { ok: true } },
            { name: `${label}-expired`, kid, alg, token: expired, expect: { ok: false, reason: 'expired' } },
            {
                name: `${label}-bad-signature`,
                kid,
                alg,
                token: flipSignatureByte(valid),
                expect: { ok: false, reason: 'bad-signature' },
            },
        );
    }

    return {
        note: 'Generated by packages/signing/src/vectors.test.ts. '
            + 'Regenerate with UPDATE_SIGNING_VECTORS=1.',
        verifyAt: VERIFY_AT,
        publicKeys: publicKeys.join(','),
        vectors,
    };
}

/** ECDSA picks a fresh nonce per signature, so an ES256 token is never byte-stable. */
function stable(file: VectorFile): unknown
{
    return {
        ...file,
        vectors: file.vectors.map((vector) => ({
            ...vector,
            token: vector.alg === 'ES256'
                ? vector.token.split('.').slice(0, 2).join('.')
                : vector.token,
        })),
    };
}

describe('signing vectors', () =>
{
    it('X2: every committed vector still produces its recorded verdict', () =>
    {
        const file = JSON.parse(readFileSync(VECTORS_FILE, 'utf8')) as VectorFile;

        expect(file.vectors).toHaveLength(6);

        for (const vector of file.vectors)
        {
            const result = verifyJws(vector.token, file.publicKeys, { now: file.verifyAt });

            expect(result, vector.name).toMatchObject(vector.expect);
        }
    });

    it('X2: regenerating reproduces the same keys, headers and payloads', async () =>
    {
        const fresh = await generate();

        if (process.env.UPDATE_SIGNING_VECTORS)
        {
            mkdirSync(dirname(VECTORS_FILE), { recursive: true });
            writeFileSync(VECTORS_FILE, `${JSON.stringify(fresh, null, 4)}\n`);
        }

        const committed = JSON.parse(readFileSync(VECTORS_FILE, 'utf8')) as VectorFile;

        expect(stable(fresh)).toEqual(stable(committed));
    });
});
