/**
 * `spfn kit recover` — unit 06 section 4.10.
 *
 * The command for a machine that cannot prove it is the machine any more:
 * the keychain item is gone, or another machine has since taken the current
 * credential and this one's is stale. Unit 04 gives one activation exactly one
 * current local client, so getting back is not "issue a second credential" —
 * it is "replace the current one, through the address the licence was bought
 * at".
 *
 * Two calls, deliberately, with a person in between:
 *
 *   1. no challenge in hand → ask the control plane to mail one, and stop.
 *      The answer is the same whether or not the activation exists, so nothing
 *      here reports whether it did.
 *   2. challenge in hand → generate the replacement locally, spend the
 *      challenge on it, and put the replacement in the keychain.
 *
 * The replacement is generated by this CLI rather than minted by the server.
 * A minted secret can be lost in the response, and losing the secret that
 * replaces a lost secret has no next step; a locally generated one can be
 * re-sent against the same challenge until an answer arrives.
 *
 * What this does not do: it does not touch the project. No file is written, no
 * operation journal is opened and no process lock is taken — recovery is
 * usually what unblocks an operation that already failed, so a recovery that
 * refused to run while one was open would be a deadlock. And it grants
 * nothing: entitlement, project limits and a revoked licence are all decided
 * by the control plane afterwards, exactly as before.
 */

import { KitError, KIT_EXIT } from './../errors.js';
import { createEventSink, type KitOperationResult } from './../events.js';
import { kitPaths } from './../paths.js';
import { readLicenseFile } from './../installed-state.js';
import { credentialPublicId, newCandidateCredential } from './../credentials.js';
import type { KitAdapters } from './../ports.js';

export interface RecoverRequest
{
    projectDir: string;
    json: boolean;
    /**
     * Reads the one-time challenge without echoing it, or is absent.
     *
     * Absent is not an error: it is the first half of the command, the half
     * that asks for the challenge to be sent. There is no `--recovery-challenge
     * <value>` option anywhere, so a challenge cannot reach a shell history or
     * a process listing.
     */
    readChallenge?: () => Promise<string>;
    write?: (line: string) => void;
}

export async function runRecover(request: RecoverRequest, adapters: KitAdapters): Promise<KitOperationResult>
{
    const secrets: string[] = [];
    const sink = createEventSink({ json: request.json, write: request.write, knownSecrets: secrets });
    const license = readLicenseFile(kitPaths(request.projectDir).licenseFile);

    if (license === null)
    {
        throw new KitError('KIT_CREDENTIAL_MISSING', 'This checkout has no activation to recover.', {
            evidence: { licenseFile: kitPaths(request.projectDir).licenseFile },
        });
    }

    if (request.readChallenge === undefined)
    {
        return await startRecovery(sink, adapters, license.activationId);
    }

    const challenge = (await request.readChallenge()).trim();

    secrets.push(challenge);

    const recoveryId = credentialPublicId(challenge);

    if (challenge === '' || recoveryId === null)
    {
        /* Refused before the control plane is asked. A malformed challenge
           cannot be the one that was mailed, and spending a request on it
           would only burn rate limit. */
        throw new KitError('CLI_RECOVERY_INVALID', 'That is not the shape of a recovery challenge.', {
            evidence: { activationId: license.activationId },
            next: { command: 'spfn kit recover --json', requiresHumanApproval: false },
        });
    }

    const replacement = newCandidateCredential();

    secrets.push(replacement);

    const completed = await adapters.license.completeRecovery({
        recoveryId,
        challenge,
        replacementCredential: replacement,
    });

    if (completed.status === 'recovery-invalid')
    {
        throw new KitError('CLI_RECOVERY_INVALID', 'That recovery challenge is not one this activation can use.', {
            evidence: { activationId: license.activationId },
            next: { command: 'spfn kit recover --json', requiresHumanApproval: false },
        });
    }
    if (completed.status === 'license-revoked')
    {
        throw new KitError('KIT_CREDENTIAL_MISSING', 'This licence no longer opens this activation.', {
            evidence: { activationId: license.activationId },
        });
    }
    if (completed.status !== 'recovered')
    {
        throw new KitError('CLI_CONTROL_PLANE_UNAVAILABLE', 'The control plane could not complete the recovery.', {
            evidence: { activationId: license.activationId, ...(completed.detail ?? {}) },
        });
    }

    /* Written before it is reported. A credential the control plane has made
       current and this machine has not stored is a credential nobody holds:
       the old one is revoked by the same call, so a report that ran first and
       a write that then failed would leave the machine worse off than before
       it recovered. */
    await adapters.credentials.save(
        {
            kitId: license.kitId,
            activationId: license.activationId,
            /* The keychain account keeps the checkout's own local name. The
               control plane's `localClientId` is its name for the client the
               replacement created, and adopting it here would orphan the item
               `.spfn/license.json` tells the next command to look in. */
            localClientId: license.localClientId,
        },
        {
            credential: replacement,
            accessExpiresAt: completed.accessExpiresAt ?? '',
            generation: completed.generation ?? 0,
        },
    );

    const summary = 'This machine holds the current credential again. The machine that held the previous one no longer does.';

    sink.emit({
        schemaVersion: 1,
        phase: 'recovery',
        status: 'completed',
        code: 'KIT_RECOVERY_COMPLETE',
        summary,
        evidence: {
            activationId: license.activationId,
            generation: completed.generation ?? 0,
            keychain: adapters.credentials.id,
        },
        next: { command: 'spfn kit restore --json', requiresHumanApproval: false },
    });

    return {
        status: 'completed',
        exitCode: KIT_EXIT.OK,
        code: 'KIT_RECOVERY_COMPLETE',
        summary,
        phase: 'recovery',
        evidence: { activationId: license.activationId, generation: completed.generation ?? 0 },
        events: sink.events,
    };
}

/** Ask for a challenge and stop. Says nothing about whether one was sent. */
async function startRecovery(
    sink: ReturnType<typeof createEventSink>,
    adapters: KitAdapters,
    activationId: string,
): Promise<KitOperationResult>
{
    const requested = await adapters.license.requestRecovery({ activationId });

    if (requested.status !== 'sent')
    {
        throw new KitError('CLI_CONTROL_PLANE_UNAVAILABLE', 'The control plane could not take the recovery request.', {
            evidence: { activationId, ...(requested.detail ?? {}) },
        });
    }

    const summary = 'If that activation exists, a one-time challenge is on its way to the address it was bought at.';

    sink.emit({
        schemaVersion: 1,
        phase: 'recovery',
        status: 'waiting',
        code: 'KIT_RECOVERY_CHALLENGE_REQUIRED',
        summary,
        evidence: { activationId, input: 'masked-stdin' },
        next: {
            command: 'spfn kit recover --recovery-challenge-stdin --json',
            requiresHumanApproval: false,
        },
    });

    return {
        status: 'waiting',
        exitCode: KIT_EXIT.INPUT_REQUIRED,
        code: 'KIT_RECOVERY_CHALLENGE_REQUIRED',
        summary,
        phase: 'recovery',
        evidence: { activationId, input: 'masked-stdin' },
        next: { command: 'spfn kit recover --recovery-challenge-stdin --json', requiresHumanApproval: false },
        events: sink.events,
    };
}
