/**
 * Application Router
 *
 * Combines all route definitions using define-route system
 */

import { defineRouter } from '@spfn/core/route';
import { getRoot } from './routes/root';
import { getHealth } from './routes/health';
import { listExamples, getExample, createExample, updateExample, deleteExample } from './routes/examples';

/**
 * Main application router
 *
 * defineRouter extracts metadata automatically.
 * Use codegen to generate router.metadata.ts for client-side usage.
 */
export const appRouter = defineRouter({
    getRoot,
    getHealth,
    listExamples,
    getExample,
    createExample,
    updateExample,
    deleteExample,
});

/**
 * Router type for client usage
 *
 * Usage:
 * ```typescript
 * import type { AppRouter } from '@/server/router';
 * import { appMetadata } from '@/server/router.metadata';  // Generated by codegen
 *
 * const api = createApi<AppRouter>({
 *   baseUrl: '/api/actions',
 *   metadata: appMetadata  // Only method/path, no server code!
 * });
 * ```
 */
export type AppRouter = typeof appRouter;
