/**
 * SPFN Configuration
 *
 * This file configures your SPFN application deployment settings.
 *
 * @type {import('spfn').SpfnConfig}
 */
export default {
  /**
   * Package manager to use for dependency installation
   * Options: 'npm' | 'yarn' | 'pnpm' | 'bun'
   */
  packageManager: 'pnpm',

  /**
   * Deployment configuration for SPFN cloud platform
   */
  deployment: {
    /**
     * Your app's subdomain on spfn.app
     *
     * This will automatically create region-specific domains:
     * - {subdomain}.{region}.spfn.app → Next.js frontend (port 3790)
     * - api-{subdomain}.{region}.spfn.app → SPFN backend (port 8790)
     *
     * Example: subdomain: 'database-crud-example', region: 'us' creates:
     * - database-crud-example.us.spfn.app
     * - api-database-crud-example.us.spfn.app
     */
    subdomain: 'database-crud-example',

    /**
     * Deployment region (optional, defaults to 'us')
     *
     * Available regions:
     * - 'us': Virginia, USA (default)
     * - 'kr': Seoul, South Korea
     * - 'jp': Tokyo, Japan [Coming soon]
     * - 'sg': Singapore [Coming soon]
     * - 'eu': Frankfurt, Germany [Coming soon]
     */
    region: 'us',

    /**
     * Custom domains (optional)
     *
     * Add your own custom domains here. Make sure to configure DNS:
     * - CNAME record pointing to spfn.app
     *
     * Example:
     * customDomains: {
     *   nextjs: ['www.example.com', 'example.com'],
     *   spfn: ['api.example.com']
     * }
     */
    customDomains: {
      /**
       * Custom domains for Next.js frontend
       */
      nextjs: [],

      /**
       * Custom domains for SPFN backend API
       */
      spfn: []
    },

    /**
     * Environment variables (optional)
     *
     * Most environment variables are auto-generated by the CI/CD pipeline.
     * Only add custom values if you need to override defaults.
     *
     * 🔧 Auto-generated variables (leave env empty for defaults):
     * - NEXT_PUBLIC_API_URL: https://api-{subdomain}.{region}.spfn.app
     *   (Used by browser/client-side code)
     * - API_URL: http://localhost:8790
     *   (Used by Next.js SSR/API Routes - same container, internal)
     *
     * 📋 When to add custom env:
     * - Using custom API domain (not *.spfn.app)
     * - Additional environment variables for your app
     *
     * ⚠️  SECURITY WARNING:
     * - These values are committed to Git
     * - Do NOT put sensitive credentials here (DB passwords, API keys, etc.)
     * - For production secrets, use your CI/CD secrets management
     *
     * Example (custom API domain):
     * env: {
     *   NEXT_PUBLIC_API_URL: 'https://api.custom.com',
     *   API_URL: 'https://api.custom.com',
     *   NEXT_PUBLIC_FEATURE_FLAG: 'true'
     * }
     */
    env: {}
  }
}
