/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-10-31T14:52:37.142Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { healthContract } from '@/lib/contracts/health';

// ============================================
// Types
// ============================================

export type HealthResponse = InferContract<typeof healthContract>['response'];

/**
 * health API
 */
export const health = {
        /**
         * GET /health
         */
        list: () => client.call(healthContract),
} as const;
