/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-10-31T14:52:37.142Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { getTeamsContract, getTeamContract, createTeamContract, updateTeamContract, deleteTeamContract } from '@/lib/contracts/teams';

// ============================================
// Types
// ============================================

export type GetTeamsResponse = InferContract<typeof getTeamsContract>['response'];

export type GetTeamResponse = InferContract<typeof getTeamContract>['response'];
export type GetTeamParams = InferContract<typeof getTeamContract>['params'];

export type CreateTeamResponse = InferContract<typeof createTeamContract>['response'];
export type CreateTeamBody = InferContract<typeof createTeamContract>['body'];

export type UpdateTeamResponse = InferContract<typeof updateTeamContract>['response'];
export type UpdateTeamParams = InferContract<typeof updateTeamContract>['params'];
export type UpdateTeamBody = InferContract<typeof updateTeamContract>['body'];

export type DeleteTeamResponse = InferContract<typeof deleteTeamContract>['response'];
export type DeleteTeamParams = InferContract<typeof deleteTeamContract>['params'];

/**
 * teams API
 */
export const teams = {
        /**
         * GET /teams
         */
        list: () => client.call(getTeamsContract),
        /**
         * GET /teams/:id
         */
        getById: (options: { params: GetTeamParams }) => client.call(getTeamContract, options),
        /**
         * POST /teams
         */
        create: (options: { body: CreateTeamBody }) => client.call(createTeamContract, options),
        /**
         * PUT /teams/:id
         */
        update: (options: { params: UpdateTeamParams, body: UpdateTeamBody }) => client.call(updateTeamContract, options),
        /**
         * DELETE /teams/:id
         */
        delete: (options: { params: DeleteTeamParams }) => client.call(deleteTeamContract, options),
} as const;
