/**
 * Auto-generated Router Metadata
 *
 * Generated by @spfn/core router codegen
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten on next generation
 */

/**
 * Route metadata extracted at build time
 *
 * This pure data object contains only method and path information,
 * making it safe to import in client-side code without bundling server logic.
 *
 * Usage:
 * ```typescript
 * import { createApi } from '@spfn/core/nextjs';
 * import { appMetadata } from '@/server/router.metadata';
 * import type { AppRouter } from '@/server/router';
 *
 * const api = createApi<AppRouter>({
 *   baseUrl: '/api/actions',
 *   metadata: appMetadata
 * });
 * ```
 */
export const appMetadata = {
    "checkAccountExists": { method: "POST", path: "/_auth/exists" },
    "sendVerificationCode": { method: "POST", path: "/_auth/codes" },
    "verifyCode": { method: "POST", path: "/_auth/codes/verify" },
    "register": { method: "POST", path: "/_auth/register" },
    "login": { method: "POST", path: "/_auth/login" },
    "logout": { method: "POST", path: "/_auth/logout" },
    "rotateKey": { method: "POST", path: "/_auth/keys/rotate" },
    "changePassword": { method: "PUT", path: "/_auth/password" },
    "getAuthSession": { method: "GET", path: "/_auth/session" },
    "getInvitation": { method: "GET", path: "/_auth/invitations/:token" },
    "acceptInvitation": { method: "POST", path: "/_auth/invitations/accept" },
    "createInvitation": { method: "POST", path: "/_auth/invitations" },
    "listInvitations": { method: "GET", path: "/_auth/invitations" },
    "cancelInvitation": { method: "POST", path: "/_auth/invitations/cancel" },
    "resendInvitation": { method: "POST", path: "/_auth/invitations/resend" },
    "deleteInvitation": { method: "POST", path: "/_auth/invitations/delete" },
    "getUserProfile": { method: "GET", path: "/_auth/users/profile" },
} as const;
