/**
 * Client Code Generator
 *
 * Generates type-safe API client code from route-contract mappings
 */

import { mkdir, writeFile } from 'fs/promises';
import { groupByResource } from './route-scanner.js';
import type { ClientGenerationOptions, GenerationStats, RouteContractMapping } from './types.js';

/**
 * Generate API client code
 */
export async function generateClient(
    mappings: RouteContractMapping[],
    options: ClientGenerationOptions
): Promise<GenerationStats>
{
    const startTime = Date.now();

    // Group by resource
    const grouped = groupByResource(mappings);
    const resourceNames = Object.keys(grouped);

    // Generate split files by resource
    await generateSplitClient(mappings, grouped, options);

    // Calculate stats
    return {
        routesScanned: mappings.length,
        contractsFound: mappings.length,
        contractFiles: countUniqueContractFiles(mappings),
        resourcesGenerated: resourceNames.length,
        methodsGenerated: mappings.length,
        duration: Date.now() - startTime
    };
}

/**
 * Generate file header
 */
function generateHeader(): string
{
    return `/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated ${new Date().toISOString()}
 */

`;
}

/**
 * Group contracts by their import path
 */
function groupContractsByImportPath(mappings: RouteContractMapping[]): Record<string, string[]>
{
    const groups: Record<string, Set<string>> = {};

    for (let i = 0; i < mappings.length; i++)
    {
        const mapping = mappings[i];
        const path = mapping.contractImportPath;

        if (!groups[path])
        {
            groups[path] = new Set();
        }

        groups[path].add(mapping.contractName);
    }

    // Convert Set to Array
    const result: Record<string, string[]> = {};
    const keys = Object.keys(groups);

    for (let i = 0; i < keys.length; i++)
    {
        const key = keys[i];
        result[key] = Array.from(groups[key]);
    }

    return result;
}

/**
 * Convert contract name to type name
 *
 * Examples:
 * - getTeamMembersContract -> GetTeamMembers
 * - createTeamMemberContract -> CreateTeamMember
 * - updateCompanyContract -> UpdateCompany
 */
function generateTypeName(mapping: RouteContractMapping): string
{
    let name = mapping.contractName;

    // Remove "Contract" suffix
    if (name.endsWith('Contract'))
    {
        name = name.slice(0, -8);
    }

    // Convert to PascalCase if not already
    if (name.length > 0)
    {
        name = name.charAt(0).toUpperCase() + name.slice(1);
    }

    return name;
}

/**
 * Generate a single method
 */
function generateMethodCode(mapping: RouteContractMapping, options: ClientGenerationOptions): string
{
    const methodName = generateMethodName(mapping);
    const hasParams = mapping.hasParams || mapping.path.includes(':');
    const hasQuery = mapping.hasQuery || false;
    const hasBody = mapping.hasBody || false;

    let code = '';

    // JSDoc
    if (options.includeJsDoc !== false)
    {
        code += `        /**\n`;
        code += `         * ${mapping.method} ${mapping.path}\n`;
        code += `         */\n`;
    }

    // Method signature
    code += `        ${methodName}: (`;

    // Parameters - use generated type names instead of InferContract
    const params: string[] = [];
    const typeName = generateTypeName(mapping);

    if (hasParams)
    {
        params.push(`params: ${typeName}Params`);
    }

    if (hasQuery)
    {
        params.push(`query?: ${typeName}Query`);
    }

    if (hasBody)
    {
        params.push(`body: ${typeName}Body`);
    }

    if (params.length > 0)
    {
        code += `options: { ${params.join(', ')} }`;
    }

    code += `) => `;

    // Call client with contract only (no basePath - contracts have absolute paths)
    code += `client.call(${mapping.contractName}`;

    if (params.length > 0)
    {
        code += `, options`;
    }

    code += `),\n`;

    return code;
}

/**
 * Generate method name from route
 */
function generateMethodName(mapping: RouteContractMapping): string
{
    const method = mapping.method.toLowerCase();

    // For index routes
    if (mapping.path === '/' || mapping.path.match(/^\/[\w-]+$/))
    {
        // Simple path like /users -> get, create, update
        if (method === 'get')
        {
            return 'list';
        }
        if (method === 'post')
        {
            return 'create';
        }
    }

    // For dynamic routes like /users/:id
    if (mapping.path.includes(':'))
    {
        if (method === 'get')
        {
            return 'getById';
        }
        if (method === 'put' || method === 'patch')
        {
            return 'update';
        }
        if (method === 'delete')
        {
            return 'delete';
        }
    }

    // Default: method name
    return method;
}

/**
 * Count unique contract files
 */
function countUniqueContractFiles(mappings: RouteContractMapping[]): number
{
    const files = new Set<string>();

    for (let i = 0; i < mappings.length; i++)
    {
        if (mappings[i].contractFile)
        {
            files.add(mappings[i].contractFile as string);
        }
    }

    return files.size;
}

/**
 * Generate split API client files by resource
 */
async function generateSplitClient(
    _mappings: RouteContractMapping[],
    grouped: Record<string, RouteContractMapping[]>,
    options: ClientGenerationOptions
): Promise<void>
{
    // When splitting, outputPath should become a directory
    // e.g., /src/lib/api.ts -> /src/lib/api/
    const outputPath = options.outputPath;
    const outputDir = outputPath.endsWith('.ts') || outputPath.endsWith('.js')
        ? outputPath.replace(/\.[jt]s$/, '')
        : outputPath;

    // Create output directory
    await mkdir(outputDir, { recursive: true });

    const resourceNames = Object.keys(grouped);

    // Generate individual resource files
    for (let i = 0; i < resourceNames.length; i++)
    {
        const resourceName = resourceNames[i];
        const routes = grouped[resourceName];

        const code = generateResourceFile(resourceName, routes, options);
        const filePath = `${outputDir}/${resourceName}.ts`;

        await writeFile(filePath, code, 'utf-8');
    }

    // Generate index file
    const indexCode = generateIndexFile(resourceNames, options);
    const indexPath = `${outputDir}/index.ts`;

    await writeFile(indexPath, indexCode, 'utf-8');
}

/**
 * Generate a single resource file
 */
function generateResourceFile(
    resourceName: string,
    routes: RouteContractMapping[],
    options: ClientGenerationOptions
): string
{
    let code = '';

    // Header
    code += generateHeader();

    // Imports
    code += `import { client } from '@spfn/core/client';\n`;

    if (options.includeTypes !== false)
    {
        code += `import type { InferContract } from '@spfn/core';\n`;
    }

    code += `\n`;

    // Contract imports
    const importGroups = groupContractsByImportPath(routes);
    const importPaths = Object.keys(importGroups);

    for (let i = 0; i < importPaths.length; i++)
    {
        const importPath = importPaths[i];
        const contracts = importGroups[importPath];

        code += `import { ${contracts.join(', ')} } from '${importPath}';\n`;
    }

    code += `\n`;

    // Types
    if (options.includeTypes !== false)
    {
        code += `// ============================================\n`;
        code += `// Types\n`;
        code += `// ============================================\n\n`;

        for (let i = 0; i < routes.length; i++)
        {
            const route = routes[i];
            const typeName = generateTypeName(route);
            const contractType = `typeof ${route.contractName}`;

            // Response type (always present)
            code += `export type ${typeName}Response = InferContract<${contractType}>['response'];\n`;

            // Query type (if exists)
            if (route.hasQuery)
            {
                code += `export type ${typeName}Query = InferContract<${contractType}>['query'];\n`;
            }

            // Params type (if exists)
            if (route.hasParams || route.path.includes(':'))
            {
                code += `export type ${typeName}Params = InferContract<${contractType}>['params'];\n`;
            }

            // Body type (if exists)
            if (route.hasBody)
            {
                code += `export type ${typeName}Body = InferContract<${contractType}>['body'];\n`;
            }

            code += `\n`;
        }
    }

    // API object
    code += `/**\n`;
    code += ` * ${resourceName} API\n`;
    code += ` */\n`;
    code += `export const ${resourceName} = {\n`;

    for (let i = 0; i < routes.length; i++)
    {
        const route = routes[i];
        code += generateMethodCode(route, options);
    }

    code += `} as const;\n`;

    return code;
}

/**
 * Generate index file that combines all resources
 */
function generateIndexFile(
    resourceNames: string[],
    _options: ClientGenerationOptions
): string
{
    let code = '';

    // Header
    code += generateHeader();

    // Re-export client
    code += `export { client } from '@spfn/core/client';\n\n`;

    // Re-export all resource modules
    for (let i = 0; i < resourceNames.length; i++)
    {
        const resourceName = resourceNames[i];
        code += `export * from './${resourceName}.js';\n`;
    }

    code += `\n`;

    // Import resources
    for (let i = 0; i < resourceNames.length; i++)
    {
        const resourceName = resourceNames[i];
        code += `import { ${resourceName} } from './${resourceName}.js';\n`;
    }

    code += `\n`;

    // Combined API object
    code += `/**\n`;
    code += ` * Type-safe API client\n`;
    code += ` */\n`;
    code += `export const api = {\n`;

    for (let i = 0; i < resourceNames.length; i++)
    {
        const resourceName = resourceNames[i];
        code += `    ${resourceName}`;

        if (i < resourceNames.length - 1)
        {
            code += `,`;
        }

        code += `\n`;
    }

    code += `} as const;\n`;

    return code;
}