import { defineConfig } from 'tsup';

export default defineConfig({
    entry: {
        'nextjs/index': 'src/nextjs/index.ts',
        'nextjs/server': 'src/nextjs/server.ts',
        'route/index': 'src/route/index.ts',
        'route/types': 'src/route/types.ts',
        'db/index': 'src/db/index.ts',
        'server/index': 'src/server/index.ts',
        'errors/index': 'src/errors/index.ts',
        'middleware/index': 'src/middleware/index.ts',
        'security/index': 'src/security/index.ts',
        'authz/index': 'src/authz/index.ts',
        'cache/index': 'src/cache/index.ts',
        'codegen/index': 'src/codegen/index.ts',
        'contract/index': 'src/contract/index.ts',
        'ops/index': 'src/ops/index.ts',
        'env/index': 'src/env/index.ts',
        'env/loader': 'src/env/loader.ts',
        'logger/index': 'src/logger/index.ts',
        'config/index': 'src/config/index.ts',
        'job/index': 'src/job/index.ts',
        'event/index': 'src/event/index.ts',
        'event/sse/index': 'src/event/sse/index.ts',
        'event/sse/client': 'src/event/sse/client.ts',
        'event/ws/index': 'src/event/ws/index.ts',
        'event/ws/client': 'src/event/ws/client.ts',
    },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: true,
    splitting: false,
    treeshake: {
        preset: 'smallest',
        propertyReadSideEffects: false,
    },
    external: [
        // Internal entrypoints (prevent bundling into each other)
        /^@spfn\//,
        // '@spfn/core/client',
        // '@spfn/core/nextjs',
        // '@spfn/core/nextjs/server',
        // '@spfn/core/route',
        // '@spfn/core/route/types',
        // '@spfn/core/db',
        // '@spfn/core/server',
        // '@spfn/core/errors',
        // '@spfn/core/middleware',
        // '@spfn/core/cache',
        // '@spfn/core/codegen',
        // '@spfn/core/env',
        // '@spfn/core/logger',
        // '@spfn/core/events',
        // '@spfn/core/config',
        // External dependencies
        'drizzle-orm',
        'hono',
        '@hono/node-server',
        'postgres',
        'ioredis',
        'ws',
        'pg-boss',
        'pino',
        'chalk',
        'chokidar',
        'dotenv',
        '@sinclair/typebox',
        'next',
        'next/server',
        'next/headers',
    ],
});
