import { defineConfig } from 'tsup';

export default defineConfig({
    entry: {
        'nextjs/index': 'src/nextjs/index.ts',
        'nextjs/server': 'src/nextjs/server.ts',
        'route/index': 'src/route/index.ts',
        'route/types': 'src/route/types.ts',
        'db/index': 'src/db/index.ts',
        'server/index': 'src/server/index.ts',
        'errors/index': 'src/errors/index.ts',
        'middleware/index': 'src/middleware/index.ts',
        'cache/index': 'src/cache/index.ts',
        'codegen/index': 'src/codegen/index.ts',
        'codegen/generators/index': 'src/codegen/generators/index.ts',
        'env/index': 'src/env/index.ts',
        'logger/index': 'src/logger/index.ts',
        'events/index': 'src/events/index.ts',
        'config/index': 'src/config/index.ts',
    },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: true,
    splitting: false,
    treeshake: {
        preset: 'smallest',
        propertyReadSideEffects: false,
    },
    external: [
        'drizzle-orm',
        'hono',
        '@hono/node-server',
        'postgres',
        'ioredis',
        'pino',
        'chalk',
        'chokidar',
        'dotenv',
        '@sinclair/typebox',
        'next',
        'next/server',
        'next/headers',
    ],
});
