/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core router codegen
 * Source: @/server/router
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten on next generation
 */

import { createApi } from '@spfn/core/client/nextjs';
import {
    ErrorRegistry,
    HttpError,
    BadRequestError,
    ValidationError,
    UnauthorizedError,
    ForbiddenError,
    NotFoundError,
    ConflictError,
    TooManyRequestsError,
    UnprocessableEntityError,
    InternalServerError,
    ServiceUnavailableError,
} from '@spfn/core/errors';
import type { AppRouter } from '@/server/router';

/**
 * Route metadata extracted at build time
 *
 * This allows the client to work without importing the actual router object,
 * making it safe to use in Server Components without bundling server code.
 */
const routeMetadata = {
    "errorNotFound": { method: "GET", path: "/errors/not-found" },
    "errorUnauthorized": { method: "GET", path: "/errors/unauthorized" },
    "errorForbidden": { method: "GET", path: "/errors/forbidden" },
    "errorConflict": { method: "POST", path: "/errors/conflict" },
    "errorUnprocessable": { method: "POST", path: "/errors/unprocessable" },
    "errorCustom": { method: "POST", path: "/errors/custom" },
    "listErrorExamples": { method: "GET", path: "/errors" },
    "listExamples": { method: "GET", path: "/examples" },
    "getExample": { method: "GET", path: "/examples/:id" },
    "createExample": { method: "POST", path: "/examples" },
    "updateExample": { method: "PUT", path: "/examples/:id" },
    "deleteExample": { method: "DELETE", path: "/examples/:id" },
    "getHealth": { method: "GET", path: "/health" },
    "getRoot": { method: "GET", path: "/" },
    "listTeams": { method: "GET", path: "/teams" },
    "getTeam": { method: "GET", path: "/teams/:id" },
    "createTeam": { method: "POST", path: "/teams" },
    "updateTeam": { method: "PUT", path: "/teams/:id" },
    "deleteTeam": { method: "DELETE", path: "/teams/:id" },
} as const;

/**
 * Error registry with built-in HTTP errors
 *
 * Enables automatic error deserialization on the client with instanceof checks.
 * To register custom errors, import them and call errorRegistry.register(CustomError).
 */
const errorRegistry = new ErrorRegistry();

// Register all built-in HTTP errors from @spfn/core
errorRegistry.registerAll([
    HttpError,
    BadRequestError,
    ValidationError,
    UnauthorizedError,
    ForbiddenError,
    NotFoundError,
    ConflictError,
    TooManyRequestsError,
    UnprocessableEntityError,
    InternalServerError,
    ServiceUnavailableError,
]);

// TODO: Register custom application errors here
// Example:
// import { CustomError } from '@/server/errors/custom-error';
// errorRegistry.register(CustomError);

/**
 * Pre-configured type-safe API client
 *
 * Usage:
 * ```typescript
 * import { api } from '@/lib/api-client';
 *
 * // Basic call
 * const user = await api.getUser
 *     .params({ id: '123' })
 *     .call();
 *
 * // Error handling with instanceof
 * try {
 *     await api.someRoute.call();
 * } catch (error) {
 *     if (error instanceof NotFoundError) {
 *         console.log('Resource not found');
 *     } else if (error instanceof ValidationError) {
 *         console.log('Validation failed:', error.fields);
 *     }
 * }
 * ```
 *
 * Works in:
 * - Server Components (no router import needed)
 * - Client Components (proxied through /api/actions)
 * - Server Actions
 * - Route Handlers
 */
export const api = createApi<AppRouter>({
    baseUrl: '/api/actions',
    metadata: routeMetadata,
    errorRegistry,
});

/**
 * Export api as default for convenience
 */
export default api;

/**
 * Export errorRegistry for registering custom errors
 */
export { errorRegistry };
