/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-10-30T04:07:08.337Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { getExamplesContract, getExampleContract, createExampleContract, updateExampleContract, deleteExampleContract } from '@/lib/contracts/examples';
import { healthContract } from '@/server/routes/health';
import { rootContract } from '@/server/routes/index';
import { getTeamsContract, getTeamContract, createTeamContract, updateTeamContract, deleteTeamContract } from '@/lib/contracts/teams';

/**
 * Type-safe API client
 */
export const api = {
    examples: {
        /**
         * GET /examples
         */
        list: (options: { query?: InferContract<typeof getExamplesContract>['query'] }) => client.call(getExamplesContract, options),
        /**
         * GET /examples/:id
         */
        getById: (options: { params: InferContract<typeof getExampleContract>['params'] }) => client.call(getExampleContract, options),
        /**
         * POST /examples
         */
        create: (options: { body: InferContract<typeof createExampleContract>['body'] }) => client.call(createExampleContract, options),
        /**
         * PUT /examples/:id
         */
        update: (options: { params: InferContract<typeof updateExampleContract>['params'], body: InferContract<typeof updateExampleContract>['body'] }) => client.call(updateExampleContract, options),
        /**
         * DELETE /examples/:id
         */
        delete: (options: { params: InferContract<typeof deleteExampleContract>['params'] }) => client.call(deleteExampleContract, options),
    },
    health.ts: {
        /**
         * GET /health.ts
         */
        get: () => client.call(healthContract),
    },
    index.ts: {
        /**
         * GET /index.ts
         */
        get: () => client.call(rootContract),
    },
    teams: {
        /**
         * GET /teams
         */
        list: () => client.call(getTeamsContract),
        /**
         * GET /teams/:id
         */
        getById: (options: { params: InferContract<typeof getTeamContract>['params'] }) => client.call(getTeamContract, options),
        /**
         * POST /teams
         */
        create: (options: { body: InferContract<typeof createTeamContract>['body'] }) => client.call(createTeamContract, options),
        /**
         * PUT /teams/:id
         */
        update: (options: { params: InferContract<typeof updateTeamContract>['params'], body: InferContract<typeof updateTeamContract>['body'] }) => client.call(updateTeamContract, options),
        /**
         * DELETE /teams/:id
         */
        delete: (options: { params: InferContract<typeof deleteTeamContract>['params'] }) => client.call(deleteTeamContract, options),
    }
} as const;

/**
 * Export client instance for advanced usage
 *
 * Use this to add interceptors or customize the client:
 *
 * @example
 * ```ts
 * import { client } from './api';
 * import { createAuthInterceptor } from '@spfn/auth/nextjs';
 * import { NextJSCookieProvider } from '@spfn/auth/nextjs';
 *
 * client.use(createAuthInterceptor({
 *   cookieProvider: new NextJSCookieProvider(),
 *   encryptionKey: process.env.ENCRYPTION_KEY!
 * }));
 * ```
 */
export { client };
