/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-10-28T10:09:51.371Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { getExamplesContract, getExampleContract, createExampleContract, updateExampleContract, deleteExampleContract } from '@/server/routes/examples/contract';
import { healthContract } from '@/server/routes/health/contract';
import { rootContract } from '@/server/routes/index/contract';
import { getTeamsContract, getTeamContract, createTeamContract, updateTeamContract, deleteTeamContract } from '@/server/routes/teams/contract';

/**
 * Type-safe API client
 */
export const api = {
    examples: {
        /**
         * GET /examples
         */
        list: (options: { query?: InferContract<typeof getExamplesContract>['query'] }) => client.call('/examples', getExamplesContract, options),
        /**
         * GET /examples/:id
         */
        getById: (options: { params: InferContract<typeof getExampleContract>['params'] }) => client.call('/examples', getExampleContract, options),
        /**
         * POST /examples
         */
        create: (options: { body: InferContract<typeof createExampleContract>['body'] }) => client.call('/examples', createExampleContract, options),
        /**
         * PUT /examples/:id
         */
        update: (options: { params: InferContract<typeof updateExampleContract>['params'], body: InferContract<typeof updateExampleContract>['body'] }) => client.call('/examples', updateExampleContract, options),
        /**
         * DELETE /examples/:id
         */
        delete: (options: { params: InferContract<typeof deleteExampleContract>['params'] }) => client.call('/examples', deleteExampleContract, options),
    },
    health: {
        /**
         * GET /health
         */
        list: () => client.call('/health', healthContract),
    },
    root: {
        /**
         * GET /
         */
        list: () => client.call('/', rootContract),
    },
    teams: {
        /**
         * GET /teams
         */
        list: () => client.call('/teams', getTeamsContract),
        /**
         * GET /teams/:id
         */
        getById: (options: { params: InferContract<typeof getTeamContract>['params'] }) => client.call('/teams', getTeamContract, options),
        /**
         * POST /teams
         */
        create: (options: { body: InferContract<typeof createTeamContract>['body'] }) => client.call('/teams', createTeamContract, options),
        /**
         * PUT /teams/:id
         */
        update: (options: { params: InferContract<typeof updateTeamContract>['params'], body: InferContract<typeof updateTeamContract>['body'] }) => client.call('/teams', updateTeamContract, options),
        /**
         * DELETE /teams/:id
         */
        delete: (options: { params: InferContract<typeof deleteTeamContract>['params'] }) => client.call('/teams', deleteTeamContract, options),
    }
} as const;

/**
 * Export client instance for advanced usage
 *
 * Use this to add interceptors or customize the client:
 *
 * @example
 * ```ts
 * import { client } from './api';
 * import { createAuthInterceptor } from '@spfn/auth/nextjs';
 * import { NextJSCookieProvider } from '@spfn/auth/nextjs';
 *
 * client.use(createAuthInterceptor({
 *   cookieProvider: new NextJSCookieProvider(),
 *   encryptionKey: process.env.ENCRYPTION_KEY!
 * }));
 * ```
 */
export { client };
