/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-10-30T07:40:48.680Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { getExamplesContract, getExampleContract, createExampleContract, updateExampleContract, deleteExampleContract } from '@/lib/contracts/examples';
import { healthContract } from '@/lib/contracts/health';
import { rootContract } from '@/lib/contracts/index';
import { getTeamsContract, getTeamContract, createTeamContract, updateTeamContract, deleteTeamContract } from '@/lib/contracts/teams';

// ============================================
// Auto-generated Types
// ============================================

export type GetExamplesResponse = InferContract<typeof getExamplesContract>['response'];
export type GetExamplesQuery = InferContract<typeof getExamplesContract>['query'];

export type GetExampleResponse = InferContract<typeof getExampleContract>['response'];
export type GetExampleParams = InferContract<typeof getExampleContract>['params'];

export type CreateExampleResponse = InferContract<typeof createExampleContract>['response'];
export type CreateExampleBody = InferContract<typeof createExampleContract>['body'];

export type UpdateExampleResponse = InferContract<typeof updateExampleContract>['response'];
export type UpdateExampleParams = InferContract<typeof updateExampleContract>['params'];
export type UpdateExampleBody = InferContract<typeof updateExampleContract>['body'];

export type DeleteExampleResponse = InferContract<typeof deleteExampleContract>['response'];
export type DeleteExampleParams = InferContract<typeof deleteExampleContract>['params'];

export type HealthResponse = InferContract<typeof healthContract>['response'];

export type RootResponse = InferContract<typeof rootContract>['response'];

export type GetTeamsResponse = InferContract<typeof getTeamsContract>['response'];

export type GetTeamResponse = InferContract<typeof getTeamContract>['response'];
export type GetTeamParams = InferContract<typeof getTeamContract>['params'];

export type CreateTeamResponse = InferContract<typeof createTeamContract>['response'];
export type CreateTeamBody = InferContract<typeof createTeamContract>['body'];

export type UpdateTeamResponse = InferContract<typeof updateTeamContract>['response'];
export type UpdateTeamParams = InferContract<typeof updateTeamContract>['params'];
export type UpdateTeamBody = InferContract<typeof updateTeamContract>['body'];

export type DeleteTeamResponse = InferContract<typeof deleteTeamContract>['response'];
export type DeleteTeamParams = InferContract<typeof deleteTeamContract>['params'];

/**
 * Type-safe API client
 */
export const api = {
    examples: {
        /**
         * GET /examples
         */
        list: (options: { query?: InferContract<typeof getExamplesContract>['query'] }) => client.call(getExamplesContract, options),
        /**
         * GET /examples/:id
         */
        getById: (options: { params: InferContract<typeof getExampleContract>['params'] }) => client.call(getExampleContract, options),
        /**
         * POST /examples
         */
        create: (options: { body: InferContract<typeof createExampleContract>['body'] }) => client.call(createExampleContract, options),
        /**
         * PUT /examples/:id
         */
        update: (options: { params: InferContract<typeof updateExampleContract>['params'], body: InferContract<typeof updateExampleContract>['body'] }) => client.call(updateExampleContract, options),
        /**
         * DELETE /examples/:id
         */
        delete: (options: { params: InferContract<typeof deleteExampleContract>['params'] }) => client.call(deleteExampleContract, options),
    },
    health: {
        /**
         * GET /health
         */
        list: () => client.call(healthContract),
    },
    root: {
        /**
         * GET /
         */
        list: () => client.call(rootContract),
    },
    teams: {
        /**
         * GET /teams
         */
        list: () => client.call(getTeamsContract),
        /**
         * GET /teams/:id
         */
        getById: (options: { params: InferContract<typeof getTeamContract>['params'] }) => client.call(getTeamContract, options),
        /**
         * POST /teams
         */
        create: (options: { body: InferContract<typeof createTeamContract>['body'] }) => client.call(createTeamContract, options),
        /**
         * PUT /teams/:id
         */
        update: (options: { params: InferContract<typeof updateTeamContract>['params'], body: InferContract<typeof updateTeamContract>['body'] }) => client.call(updateTeamContract, options),
        /**
         * DELETE /teams/:id
         */
        delete: (options: { params: InferContract<typeof deleteTeamContract>['params'] }) => client.call(deleteTeamContract, options),
    }
} as const;

/**
 * Export client instance for advanced usage
 *
 * Use this to add interceptors or customize the client:
 *
 * @example
 * ```ts
 * import { client } from './api';
 * import { createAuthInterceptor } from '@spfn/auth/nextjs';
 * import { NextJSCookieProvider } from '@spfn/auth/nextjs';
 *
 * client.use(createAuthInterceptor({
 *   cookieProvider: new NextJSCookieProvider(),
 *   encryptionKey: process.env.ENCRYPTION_KEY!
 * }));
 * ```
 */
export { client };
