/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-10-31T14:50:47.279Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { getExamplesContract, getExampleContract, createExampleContract, updateExampleContract, deleteExampleContract } from '@/lib/contracts/examples';

// ============================================
// Types
// ============================================

export type GetExamplesResponse = InferContract<typeof getExamplesContract>['response'];
export type GetExamplesQuery = InferContract<typeof getExamplesContract>['query'];

export type GetExampleResponse = InferContract<typeof getExampleContract>['response'];
export type GetExampleParams = InferContract<typeof getExampleContract>['params'];

export type CreateExampleResponse = InferContract<typeof createExampleContract>['response'];
export type CreateExampleBody = InferContract<typeof createExampleContract>['body'];

export type UpdateExampleResponse = InferContract<typeof updateExampleContract>['response'];
export type UpdateExampleParams = InferContract<typeof updateExampleContract>['params'];
export type UpdateExampleBody = InferContract<typeof updateExampleContract>['body'];

export type DeleteExampleResponse = InferContract<typeof deleteExampleContract>['response'];
export type DeleteExampleParams = InferContract<typeof deleteExampleContract>['params'];

/**
 * examples API
 */
export const examples = {
        /**
         * GET /examples
         */
        list: (options: { query?: GetExamplesQuery }) => client.call(getExamplesContract, options),
        /**
         * GET /examples/:id
         */
        getById: (options: { params: GetExampleParams }) => client.call(getExampleContract, options),
        /**
         * POST /examples
         */
        create: (options: { body: CreateExampleBody }) => client.call(createExampleContract, options),
        /**
         * PUT /examples/:id
         */
        update: (options: { params: UpdateExampleParams, body: UpdateExampleBody }) => client.call(updateExampleContract, options),
        /**
         * DELETE /examples/:id
         */
        delete: (options: { params: DeleteExampleParams }) => client.call(deleteExampleContract, options),
} as const;
