/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-10-31T14:50:47.281Z
 */

export { client } from '@spfn/core/client';

export * from './examples.js';
export * from './health.js';
export * from './root.js';
export * from './teams.js';

import { examples } from './examples.js';
import { health } from './health.js';
import { root } from './root.js';
import { teams } from './teams.js';

/**
 * Type-safe API client
 */
export const api = {
    examples,
    health,
    root,
    teams
} as const;
