/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated 2025-10-31T14:50:47.280Z
 */

import { client } from '@spfn/core/client';
import type { InferContract } from '@spfn/core';

import { rootContract } from '@/lib/contracts/index';

// ============================================
// Types
// ============================================

export type RootResponse = InferContract<typeof rootContract>['response'];

/**
 * root API
 */
export const root = {
        /**
         * GET /
         */
        list: () => client.call(rootContract),
} as const;
