/**
 * Client Code Generator
 *
 * Generates type-safe API client code from route-contract mappings
 */

import { mkdir, writeFile } from 'fs/promises';
import { groupByResource } from './helpers';
import type { ClientGenerationOptions, GenerationStats, RouteContractMapping } from '../../core/types';

/**
 * Generate API client code
 */
export async function generateClient(
    mappings: RouteContractMapping[],
    options: ClientGenerationOptions
): Promise<GenerationStats>
{
    const startTime = Date.now();

    // Group by resource
    const grouped = groupByResource(mappings);
    const resourceNames = Object.keys(grouped);

    // Generate split files by resource
    await generateSplitClient(mappings, grouped, options);

    // Calculate stats
    return {
        routesScanned: mappings.length,
        contractsFound: mappings.length,
        contractFiles: countUniqueContractFiles(mappings),
        resourcesGenerated: resourceNames.length,
        methodsGenerated: mappings.length,
        duration: Date.now() - startTime
    };
}

/**
 * Generate file header
 */
function generateHeader(): string
{
    return `/**
 * Auto-generated API Client
 *
 * Generated by @spfn/core codegen
 * DO NOT EDIT MANUALLY
 *
 * @generated ${new Date().toISOString()}
 */

`;
}

/**
 * Group contracts by their import path
 */
function groupContractsByImportPath(mappings: RouteContractMapping[]): Record<string, string[]>
{
    const groups: Record<string, Set<string>> = {};

    for (let i = 0; i < mappings.length; i++)
    {
        const mapping = mappings[i];
        const path = mapping.contractImportPath;

        if (!groups[path])
        {
            groups[path] = new Set();
        }

        groups[path].add(mapping.contractName);
    }

    // Convert Set to Array
    const result: Record<string, string[]> = {};
    const keys = Object.keys(groups);

    for (let i = 0; i < keys.length; i++)
    {
        const key = keys[i];
        result[key] = Array.from(groups[key]);
    }

    return result;
}

/**
 * Convert contract name to type name
 *
 * Examples:
 * - getTeamMembersContract -> GetTeamMembers
 * - createTeamMemberContract -> CreateTeamMember
 * - updateCompanyContract -> UpdateCompany
 */
function generateTypeName(mapping: RouteContractMapping): string
{
    let name = mapping.contractName;

    // Remove "Contract" suffix
    if (name.endsWith('Contract'))
    {
        name = name.slice(0, -8);
    }

    // Convert to PascalCase if not already
    if (name.length > 0)
    {
        name = name.charAt(0).toUpperCase() + name.slice(1);
    }

    return name;
}

/**
 * Generate function name from contract name
 *
 * Examples:
 * - getLabelsContract -> getLabels
 * - createLabelContract -> createLabel
 * - updateLabelContract -> updateLabel
 */
function generateFunctionName(mapping: RouteContractMapping): string
{
    let name = mapping.contractName;

    // Remove "Contract" suffix
    if (name.endsWith('Contract'))
    {
        name = name.slice(0, -8);
    }

    return name;
}

/**
 * Generate a single function export
 */
function generateFunctionCode(mapping: RouteContractMapping, options: ClientGenerationOptions): string
{
    const functionName = generateFunctionName(mapping);
    const hasParams = mapping.hasParams || mapping.path.includes(':');
    const hasQuery = mapping.hasQuery || false;
    const hasBody = mapping.hasBody || false;

    let code = '';

    // JSDoc
    if (options.includeJsDoc !== false)
    {
        code += `/**\n`;
        code += ` * ${mapping.method} ${mapping.path}\n`;
        code += ` */\n`;
    }

    // Function signature
    code += `export const ${functionName} = (`;

    // Parameters - use generated type names instead of InferContract
    const params: string[] = [];
    const typeName = generateTypeName(mapping);

    if (hasParams)
    {
        params.push(`params: ${typeName}Params`);
    }

    if (hasQuery)
    {
        params.push(`query?: ${typeName}Query`);
    }

    if (hasBody)
    {
        params.push(`body: ${typeName}Body`);
    }

    if (params.length > 0)
    {
        code += `options: { ${params.join(', ')} }`;
    }

    code += `) => `;

    // Call client with contract only (no basePath - contracts have absolute paths)
    code += `client.call(${mapping.contractName}`;

    if (params.length > 0)
    {
        code += `, options`;
    }

    code += `);\n\n`;

    return code;
}

/**
 * Count unique contract files
 */
function countUniqueContractFiles(mappings: RouteContractMapping[]): number
{
    const files = new Set<string>();

    for (let i = 0; i < mappings.length; i++)
    {
        if (mappings[i].contractFile)
        {
            files.add(mappings[i].contractFile as string);
        }
    }

    return files.size;
}

/**
 * Convert camelCase to kebab-case
 *
 * Examples:
 * - labels -> labels
 * - publishedCache -> published-cache
 * - usersPosts -> users-posts
 */
function toKebabCase(str: string): string
{
    if (str.length === 0)
    {
        return str;
    }

    return str
        .replace(/([a-z])([A-Z])/g, '$1-$2')
        .toLowerCase();
}

/**
 * Generate split API client files by resource
 */
async function generateSplitClient(
    _mappings: RouteContractMapping[],
    grouped: Record<string, RouteContractMapping[]>,
    options: ClientGenerationOptions
): Promise<void>
{
    // When splitting, outputPath should become a directory
    // e.g., /src/lib/api.ts -> /src/lib/api/
    const outputPath = options.outputPath;
    const outputDir = outputPath.endsWith('.ts') || outputPath.endsWith('.js')
        ? outputPath.replace(/\.[jt]s$/, '')
        : outputPath;

    // Create output directory
    await mkdir(outputDir, { recursive: true });

    const resourceNames = Object.keys(grouped);

    // Generate individual resource files
    for (let i = 0; i < resourceNames.length; i++)
    {
        const resourceName = resourceNames[i];
        const routes = grouped[resourceName];

        const code = generateResourceFile(resourceName, routes, options);
        // Convert to kebab-case for file name
        const kebabName = toKebabCase(resourceName);
        const filePath = `${outputDir}/${kebabName}.ts`;

        await writeFile(filePath, code, 'utf-8');
    }

    // Generate index file
    const indexCode = generateIndexFile(grouped, options);
    const indexPath = `${outputDir}/index.ts`;

    await writeFile(indexPath, indexCode, 'utf-8');
}

/**
 * Generate a single resource file
 */
function generateResourceFile(
    _resourceName: string,
    routes: RouteContractMapping[],
    options: ClientGenerationOptions
): string
{
    let code = '';

    // Header
    code += generateHeader();

    // Imports
    code += `import { client } from '@spfn/core/client';\n`;

    if (options.includeTypes !== false)
    {
        code += `import type { InferContract } from '@spfn/core';\n`;
    }

    code += `\n`;

    // Contract imports
    const importGroups = groupContractsByImportPath(routes);
    const importPaths = Object.keys(importGroups);

    for (let i = 0; i < importPaths.length; i++)
    {
        const importPath = importPaths[i];
        const contracts = importGroups[importPath];

        code += `import { ${contracts.join(', ')} } from '${importPath}';\n`;
    }

    code += `\n`;

    // Types
    if (options.includeTypes !== false)
    {
        code += `// ============================================\n`;
        code += `// Types\n`;
        code += `// ============================================\n\n`;

        for (let i = 0; i < routes.length; i++)
        {
            const route = routes[i];
            const typeName = generateTypeName(route);
            const contractType = `typeof ${route.contractName}`;

            // Response type (always present)
            code += `export type ${typeName}Response = InferContract<${contractType}>['response'];\n`;

            // Query type (if exists)
            if (route.hasQuery)
            {
                code += `export type ${typeName}Query = InferContract<${contractType}>['query'];\n`;
            }

            // Params type (if exists)
            if (route.hasParams || route.path.includes(':'))
            {
                code += `export type ${typeName}Params = InferContract<${contractType}>['params'];\n`;
            }

            // Body type (if exists)
            if (route.hasBody)
            {
                code += `export type ${typeName}Body = InferContract<${contractType}>['body'];\n`;
            }

            code += `\n`;
        }
    }

    // Generate individual function exports
    code += `// ============================================\n`;
    code += `// API Functions\n`;
    code += `// ============================================\n\n`;

    for (let i = 0; i < routes.length; i++)
    {
        const route = routes[i];
        code += generateFunctionCode(route, options);
    }

    return code;
}

/**
 * Generate index file that combines all resources
 */
function generateIndexFile(
    grouped: Record<string, RouteContractMapping[]>,
    options: ClientGenerationOptions
): string
{
    let code = '';
    const apiName = options.apiName || 'api';
    const resourceNames = Object.keys(grouped);

    // Header
    code += generateHeader();

    // Re-export client
    code += `export { client } from '@spfn/core/client';\n\n`;

    // Re-export only types from resource modules (use kebab-case for file names)
    for (let i = 0; i < resourceNames.length; i++)
    {
        const resourceName = resourceNames[i];
        const routes = grouped[resourceName];
        const kebabName = toKebabCase(resourceName);

        // Collect all type names for this resource
        const typeNames: string[] = [];
        for (let j = 0; j < routes.length; j++)
        {
            const route = routes[j];
            const typeName = generateTypeName(route);

            // Always export Response type
            typeNames.push(`${typeName}Response`);

            // Conditionally export other types
            if (route.hasQuery)
            {
                typeNames.push(`${typeName}Query`);
            }
            if (route.hasParams || route.path.includes(':'))
            {
                typeNames.push(`${typeName}Params`);
            }
            if (route.hasBody)
            {
                typeNames.push(`${typeName}Body`);
            }
        }

        if (typeNames.length > 0)
        {
            code += `export type { ${typeNames.join(', ')} } from './${kebabName}.js';\n`;
        }
    }

    code += `\n`;

    // Import all functions from each resource file
    for (let i = 0; i < resourceNames.length; i++)
    {
        const resourceName = resourceNames[i];
        const routes = grouped[resourceName];
        const kebabName = toKebabCase(resourceName);

        // Get all function names for this resource
        const functionNames = routes.map(route => generateFunctionName(route));

        code += `import { ${functionNames.join(', ')} } from './${kebabName}.js';\n`;
    }

    code += `\n`;

    // Combined API object with all functions flattened
    code += `/**\n`;
    code += ` * Type-safe API client\n`;
    code += ` */\n`;
    code += `export const ${apiName} = {\n`;

    // Add all functions from all resources
    let isFirst = true;
    for (let i = 0; i < resourceNames.length; i++)
    {
        const resourceName = resourceNames[i];
        const routes = grouped[resourceName];

        for (let j = 0; j < routes.length; j++)
        {
            const route = routes[j];
            const functionName = generateFunctionName(route);

            if (!isFirst)
            {
                code += `,\n`;
            }

            code += `    ${functionName}`;
            isFirst = false;
        }
    }

    code += `\n} as const;\n`;

    return code;
}