/**
 * Auto-generated Router Metadata
 *
 * Generated by @spfn/core router codegen
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten on next generation
 */

/**
 * Route metadata extracted at build time
 *
 * This pure data object contains only method and path information,
 * making it safe to import in client-side code without bundling server logic.
 *
 * Usage:
 * ```typescript
 * import { createApi } from '@spfn/core/nextjs';
 * import { appMetadata } from '@/server/router.metadata';
 * import type { AppRouter } from '@/server/router';
 *
 * const api = createApi<AppRouter>({
 *   baseUrl: '/api/actions',
 *   metadata: appMetadata
 * });
 * ```
 */
export const appMetadata = {
    "getLabelCache": { method: "GET", path: "/_cms/labels/cache" },
} as const;
