/**
 * Auto-generated Router Metadata
 *
 * Generated by @spfn/core router codegen
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten on next generation
 */

/**
 * Route metadata extracted at build time
 *
 * This pure data object contains only method and path information,
 * making it safe to import in client-side code without bundling server logic.
 *
 * Usage:
 * ```typescript
 * import { createApi } from '@spfn/core/nextjs';
 * import { appMetadata } from '@/server/router.metadata';
 * import type { AppRouter } from '@/server/router';
 *
 * const api = createApi<AppRouter>({
 *   baseUrl: '/api/actions',
 *   metadata: appMetadata
 * });
 * ```
 */
export const appMetadata = {
    "getLabels": { method: "GET", path: "/_cms/labels" },
    "createLabel": { method: "POST", path: "/_cms/labels" },
    "getLabel": { method: "GET", path: "/_cms/labels/:id" },
    "updateLabel": { method: "PATCH", path: "/_cms/labels/:id" },
    "deleteLabel": { method: "DELETE", path: "/_cms/labels/:id" },
    "getLabelByKeyRoute": { method: "GET", path: "/_cms/labels/by-key/:key" },
    "publishLabel": { method: "POST", path: "/_cms/labels/:id/publish" },
    "getAdminLabel": { method: "GET", path: "/_cms/labels/:id/admin" },
    "getLabelVersions": { method: "GET", path: "/_cms/labels/:id/versions" },
    "getPublishedCache": { method: "GET", path: "/_cms/published-cache" },
    "upsertCache": { method: "POST", path: "/_cms/published-cache" },
    "saveValues": { method: "POST", path: "/_cms/values/:labelId" },
    "getValues": { method: "GET", path: "/_cms/values/:labelId/:version" },
} as const;
