name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build --filter="!./apps/*"

      - name: Type check
        run: pnpm --filter "./packages/*" type-check

      - name: Lint
        run: pnpm lint

      - name: Start test infrastructure
        run: docker compose -f docker-compose.test.yml up -d

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for PostgreSQL..."
          timeout 30 bash -c 'until docker exec spfn-test-postgres pg_isready -U testuser -d spfn_test; do sleep 1; done'
          echo "Waiting for Redis..."
          timeout 30 bash -c 'until docker exec spfn-redis-single redis-cli ping; do sleep 1; done'

      - name: Test
        run: pnpm test
        env:
          DATABASE_URL: postgresql://testuser:testpass@localhost:5433/spfn_test
          REDIS_URL: redis://localhost:6379

      - name: Stop test infrastructure
        if: always()
        run: docker compose -f docker-compose.test.yml down -v