name: Publish Packages

on:
  push:
    tags:
      - 'v*' # v로 시작하는 모든 태그 (v0.1.0-alpha.3 등)

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # GitHub Packages 배포 권한

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build packages
        run: npm run build

      # npm 배포
      - name: Publish to npm
        run: |
          cd packages/core
          npm publish --access public
          cd ../spfn
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # GitHub Packages 배포
      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@spfn'

      - name: Publish to GitHub Packages
        run: |
          cd packages/core
          npm publish --access public
          cd ../spfn
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}