name: Publish Packages

on:
  push:
    tags:
      - 'v*' # v로 시작하는 모든 태그 (v0.1.0-alpha.3 등)

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # npm provenance를 위한 OIDC 토큰 권한

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Update npm to latest
        run: npm install -g npm@latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      # npm 배포 (OIDC Trusted Publisher 사용)
      - name: Publish @spfn/core to npm
        working-directory: packages/core
        run: npm publish --access public --provenance

      - name: Publish spfn to npm
        working-directory: packages/spfn
        run: npm publish --access public --provenance